#!/usr/bin/env node

const fs = require('fs')

// Complete API key on ONE LINE (verified working)
const COMPLETE_API_KEY = `OPENAI_API_KEY=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`

function createCleanEnvFile(filePath) {
  console.log(`🔧 Creating clean ${filePath}...`)
  
  // Basic environment template (without API key)
  const baseContent = `# Helfi App Environment Variables
# Generated by bulletproof-api-fix.js

# Database
DATABASE_URL="file:./dev.db"

# NextAuth
NEXTAUTH_SECRET="your-secret-here"
NEXTAUTH_URL="http://localhost:3000"

# Resend Email Service Configuration
RESEND_API_KEY=your_resend_api_key_here_get_from_resend_com

# OpenAI API Key (BULLETPROOF - SINGLE LINE)
${COMPLETE_API_KEY}
`

  // Write the complete file at once
  fs.writeFileSync(filePath, baseContent, 'utf8')
  
  // Verify it was written correctly
  const verification = fs.readFileSync(filePath, 'utf8')
  if (verification.includes(COMPLETE_API_KEY)) {
    console.log(`✅ Successfully created ${filePath} with single-line API key`)
    return true
  } else {
    console.log(`❌ Failed to write ${filePath} correctly`)
    return false
  }
}

function validateSingleLine(filePath) {
  console.log(`🔍 Validating ${filePath}...`)
  
  const content = fs.readFileSync(filePath, 'utf8')
  const lines = content.split('\n')
  
  // Find the API key line
  const apiKeyLine = lines.find(line => line.startsWith('OPENAI_API_KEY='))
  
  if (!apiKeyLine) {
    console.log(`❌ No API key found in ${filePath}`)
    return false
  }
  
  if (apiKeyLine === COMPLETE_API_KEY) {
    console.log(`✅ API key is perfect single line in ${filePath}`)
    return true
  } else {
    console.log(`❌ API key is corrupted in ${filePath}`)
    console.log(`Expected length: ${COMPLETE_API_KEY.length}`)
    console.log(`Actual length:   ${apiKeyLine.length}`)
    return false
  }
}

function main() {
  console.log('🚀 BULLETPROOF API KEY FIX')
  console.log('This will completely recreate environment files with proper API key\n')
  
  const files = ['.env.local', '.env']
  let allSuccess = true
  
  // Create clean files
  for (const file of files) {
    if (!createCleanEnvFile(file)) {
      allSuccess = false
    }
  }
  
  console.log('\n🔍 Final validation...')
  
  // Validate all files
  for (const file of files) {
    if (!validateSingleLine(file)) {
      allSuccess = false
    }
  }
  
  if (allSuccess) {
    console.log('\n🎉 SUCCESS! API key is now bulletproof!')
    console.log('💡 The API key is guaranteed to be on a single line')
    console.log('💡 Run "npm run fix-api" anytime this happens again')
    console.log('\n🔄 Please restart your development server now')
  } else {
    console.log('\n❌ Something went wrong')
    process.exit(1)
  }
}

if (require.main === module) {
  main()
}

module.exports = { createCleanEnvFile, validateSingleLine } 