export type ProduceMeasurement = {
  food: string;
  category: string;
  subtype: string;
  density_confidence: string;
  raw_cup_g: number | null;
  quarter_cup_raw_g: number | null;
  half_cup_raw_g: number | null;
  three_quarter_cup_raw_g: number | null;
  cooked_cup_g: number | null;
  quarter_cup_cooked_g: number | null;
  half_cup_cooked_g: number | null;
  three_quarter_cup_cooked_g: number | null;
  piece_small_g: number | null;
  piece_medium_g: number | null;
  piece_large_g: number | null;
};

export const PRODUCE_MEASUREMENTS: ProduceMeasurement[] = [
  {
    "food": "Acai",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Apple",
    "category": "fruit",
    "subtype": "pome",
    "density_confidence": "high",
    "raw_cup_g": 135,
    "quarter_cup_raw_g": 33.8,
    "half_cup_raw_g": 67.5,
    "three_quarter_cup_raw_g": 101.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 140,
    "piece_medium_g": 180,
    "piece_large_g": 220
  },
  {
    "food": "Apricot",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": 35,
    "piece_medium_g": 45,
    "piece_large_g": 55
  },
  {
    "food": "Atemoya",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Avocado",
    "category": "fruit",
    "subtype": "avocado",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 120,
    "piece_medium_g": 170,
    "piece_large_g": 230
  },
  {
    "food": "Banana",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 100,
    "piece_medium_g": 120,
    "piece_large_g": 140
  },
  {
    "food": "Barberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bergamot",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bilberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Blackberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Blueberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Boysenberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Breadfruit",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cactus pear (prickly pear)",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Camu camu",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cantaloupe",
    "category": "fruit",
    "subtype": "melon",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 350,
    "piece_medium_g": 550,
    "piece_large_g": 800
  },
  {
    "food": "Cherimoya",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cherry",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Citron",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Clementine",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cloudberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Coconut meat",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Concord grape",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cranberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Currant (black)",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Currant (red)",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Currant (white)",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Date (fresh)",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Dragon fruit",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Durian",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Elderberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Feijoa",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Fig",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 45,
    "piece_medium_g": 55,
    "piece_large_g": 70
  },
  {
    "food": "Galia melon",
    "category": "fruit",
    "subtype": "melon",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Gooseberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Grapefruit",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 230,
    "piece_medium_g": 300,
    "piece_large_g": 380
  },
  {
    "food": "Grapes",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Guava",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 150,
    "piece_medium_g": 200,
    "piece_large_g": 260
  },
  {
    "food": "Honeydew",
    "category": "fruit",
    "subtype": "melon",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 350,
    "piece_medium_g": 550,
    "piece_large_g": 800
  },
  {
    "food": "Huckleberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Jackfruit",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Jujube",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Kiwi",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": 70,
    "piece_medium_g": 90,
    "piece_large_g": 110
  },
  {
    "food": "Kiwifruit",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": 70,
    "piece_medium_g": 90,
    "piece_large_g": 110
  },
  {
    "food": "Kumquat",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Langsat",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Lemon",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 80,
    "piece_medium_g": 110,
    "piece_large_g": 140
  },
  {
    "food": "Lime",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 55,
    "piece_medium_g": 70,
    "piece_large_g": 90
  },
  {
    "food": "Lingonberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Longan",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Loquat",
    "category": "fruit",
    "subtype": "pome",
    "density_confidence": "high",
    "raw_cup_g": 135,
    "quarter_cup_raw_g": 33.8,
    "half_cup_raw_g": 67.5,
    "three_quarter_cup_raw_g": 101.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Lucuma",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Lychee",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mamey sapote",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mandarin",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 80,
    "piece_medium_g": 100,
    "piece_large_g": 120
  },
  {
    "food": "Mango",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": 200,
    "piece_medium_g": 280,
    "piece_large_g": 360
  },
  {
    "food": "Mango (stone fruit)",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mangosteen",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Medlar",
    "category": "fruit",
    "subtype": "pome",
    "density_confidence": "high",
    "raw_cup_g": 135,
    "quarter_cup_raw_g": 33.8,
    "half_cup_raw_g": 67.5,
    "three_quarter_cup_raw_g": 101.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mulberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Nance",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Nectarine",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Olive",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Orange",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 130,
    "piece_medium_g": 160,
    "piece_large_g": 200
  },
  {
    "food": "Papaya",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 500,
    "piece_medium_g": 750,
    "piece_large_g": 1000
  },
  {
    "food": "Passionfruit",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 18,
    "piece_medium_g": 25,
    "piece_large_g": 32
  },
  {
    "food": "Peach",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": 130,
    "piece_medium_g": 160,
    "piece_large_g": 190
  },
  {
    "food": "Pear",
    "category": "fruit",
    "subtype": "pome",
    "density_confidence": "high",
    "raw_cup_g": 135,
    "quarter_cup_raw_g": 33.8,
    "half_cup_raw_g": 67.5,
    "three_quarter_cup_raw_g": 101.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 150,
    "piece_medium_g": 190,
    "piece_large_g": 230
  },
  {
    "food": "Persimmon",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Pineapple",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": 600,
    "piece_medium_g": 900,
    "piece_large_g": 1200
  },
  {
    "food": "Pitaya",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Plantain",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": 140,
    "piece_medium_g": 200,
    "piece_large_g": 260
  },
  {
    "food": "Plum",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": 90,
    "piece_medium_g": 110,
    "piece_large_g": 130
  },
  {
    "food": "Pomegranate",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": 190,
    "piece_medium_g": 260,
    "piece_large_g": 340
  },
  {
    "food": "Pomelo",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Quince",
    "category": "fruit",
    "subtype": "pome",
    "density_confidence": "high",
    "raw_cup_g": 135,
    "quarter_cup_raw_g": 33.8,
    "half_cup_raw_g": 67.5,
    "three_quarter_cup_raw_g": 101.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Rambutan",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Raspberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Salak (snake fruit)",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Sapodilla",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Sour cherry",
    "category": "fruit",
    "subtype": "stone_fruit",
    "density_confidence": "medium",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 170,
    "quarter_cup_cooked_g": 42.5,
    "half_cup_cooked_g": 85,
    "three_quarter_cup_cooked_g": 127.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Soursop (graviola)",
    "category": "fruit",
    "subtype": "tropical_soft",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 165,
    "quarter_cup_cooked_g": 41.2,
    "half_cup_cooked_g": 82.5,
    "three_quarter_cup_cooked_g": 123.8,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Starfruit (carambola)",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Strawberry",
    "category": "fruit",
    "subtype": "berry",
    "density_confidence": "high",
    "raw_cup_g": 145,
    "quarter_cup_raw_g": 36.2,
    "half_cup_raw_g": 72.5,
    "three_quarter_cup_raw_g": 108.8,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Tamarind",
    "category": "fruit",
    "subtype": "tropical_firm",
    "density_confidence": "medium",
    "raw_cup_g": 165,
    "quarter_cup_raw_g": 41.2,
    "half_cup_raw_g": 82.5,
    "three_quarter_cup_raw_g": 123.8,
    "cooked_cup_g": 175,
    "quarter_cup_cooked_g": 43.8,
    "half_cup_cooked_g": 87.5,
    "three_quarter_cup_cooked_g": 131.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Tangerine",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Watermelon",
    "category": "fruit",
    "subtype": "melon",
    "density_confidence": "medium",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 400,
    "piece_medium_g": 700,
    "piece_large_g": 1000
  },
  {
    "food": "Yuzu",
    "category": "fruit",
    "subtype": "citrus_segments",
    "density_confidence": "medium",
    "raw_cup_g": 175,
    "quarter_cup_raw_g": 43.8,
    "half_cup_raw_g": 87.5,
    "three_quarter_cup_raw_g": 131.2,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Acorn squash",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Arrowroot",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Artichoke",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Asparagus",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Aubergine (eggplant)",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bamboo shoots",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Basil",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bean sprouts",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Beet greens",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Beetroot",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 120,
    "piece_medium_g": 170,
    "piece_large_g": 230
  },
  {
    "food": "Bitter melon",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bok choy",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Bottle gourd",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Broccoli",
    "category": "vegetable",
    "subtype": "cruciferous",
    "density_confidence": "high",
    "raw_cup_g": 95,
    "quarter_cup_raw_g": 23.8,
    "half_cup_raw_g": 47.5,
    "three_quarter_cup_raw_g": 71.2,
    "cooked_cup_g": 155,
    "quarter_cup_cooked_g": 38.8,
    "half_cup_cooked_g": 77.5,
    "three_quarter_cup_cooked_g": 116.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Broccolini",
    "category": "vegetable",
    "subtype": "cruciferous",
    "density_confidence": "high",
    "raw_cup_g": 95,
    "quarter_cup_raw_g": 23.8,
    "half_cup_raw_g": 47.5,
    "three_quarter_cup_raw_g": 71.2,
    "cooked_cup_g": 155,
    "quarter_cup_cooked_g": 38.8,
    "half_cup_cooked_g": 77.5,
    "three_quarter_cup_cooked_g": 116.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Brussels sprouts",
    "category": "vegetable",
    "subtype": "cruciferous",
    "density_confidence": "high",
    "raw_cup_g": 95,
    "quarter_cup_raw_g": 23.8,
    "half_cup_raw_g": 47.5,
    "three_quarter_cup_raw_g": 71.2,
    "cooked_cup_g": 155,
    "quarter_cup_cooked_g": 38.8,
    "half_cup_cooked_g": 77.5,
    "three_quarter_cup_cooked_g": 116.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Butternut squash",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cabbage",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Capsicum (hot)",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Capsicum / Bell pepper",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": 120,
    "piece_medium_g": 160,
    "piece_large_g": 220
  },
  {
    "food": "Carrot",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 60,
    "piece_medium_g": 90,
    "piece_large_g": 130
  },
  {
    "food": "Cassava / yuca",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cauliflower",
    "category": "vegetable",
    "subtype": "cruciferous",
    "density_confidence": "high",
    "raw_cup_g": 95,
    "quarter_cup_raw_g": 23.8,
    "half_cup_raw_g": 47.5,
    "three_quarter_cup_raw_g": 71.2,
    "cooked_cup_g": 155,
    "quarter_cup_cooked_g": 38.8,
    "half_cup_cooked_g": 77.5,
    "three_quarter_cup_cooked_g": 116.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Celeriac",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Celery",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Chayote",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cherry tomato",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Chilli pepper",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Chive",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Choy sum",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Collard greens",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Coriander leaves (cilantro)",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Corn kernels",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Cucumber",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 200,
    "piece_medium_g": 300,
    "piece_large_g": 400
  },
  {
    "food": "Daikon",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Dill",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Edamame",
    "category": "vegetable",
    "subtype": "legume_green",
    "density_confidence": "high",
    "raw_cup_g": 100,
    "quarter_cup_raw_g": 25,
    "half_cup_raw_g": 50,
    "three_quarter_cup_raw_g": 75,
    "cooked_cup_g": 135,
    "quarter_cup_cooked_g": 33.8,
    "half_cup_cooked_g": 67.5,
    "three_quarter_cup_cooked_g": 101.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Eggplant",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": 250,
    "piece_medium_g": 350,
    "piece_large_g": 500
  },
  {
    "food": "Endive",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Fennel",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Garlic",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Ginger root",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Green beans",
    "category": "vegetable",
    "subtype": "legume_green",
    "density_confidence": "high",
    "raw_cup_g": 100,
    "quarter_cup_raw_g": 25,
    "half_cup_raw_g": 50,
    "three_quarter_cup_raw_g": 75,
    "cooked_cup_g": 135,
    "quarter_cup_cooked_g": 33.8,
    "half_cup_cooked_g": 67.5,
    "three_quarter_cup_cooked_g": 101.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Iceberg lettuce",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Jicama",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Kale",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Kohlrabi",
    "category": "vegetable",
    "subtype": "cruciferous",
    "density_confidence": "high",
    "raw_cup_g": 95,
    "quarter_cup_raw_g": 23.8,
    "half_cup_raw_g": 47.5,
    "three_quarter_cup_raw_g": 71.2,
    "cooked_cup_g": 155,
    "quarter_cup_cooked_g": 38.8,
    "half_cup_cooked_g": 77.5,
    "three_quarter_cup_cooked_g": 116.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Kombu (seaweed)",
    "category": "vegetable",
    "subtype": "sea_veg",
    "density_confidence": "low",
    "raw_cup_g": 50,
    "quarter_cup_raw_g": 12.5,
    "half_cup_raw_g": 25,
    "three_quarter_cup_raw_g": 37.5,
    "cooked_cup_g": 100,
    "quarter_cup_cooked_g": 25,
    "half_cup_cooked_g": 50,
    "three_quarter_cup_cooked_g": 75,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Leek",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": 120,
    "piece_medium_g": 180,
    "piece_large_g": 260
  },
  {
    "food": "Lettuce",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Lotus root",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Microgreens (mixed)",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mint",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mushroom (button)",
    "category": "vegetable",
    "subtype": "mushroom",
    "density_confidence": "medium",
    "raw_cup_g": 70,
    "quarter_cup_raw_g": 17.5,
    "half_cup_raw_g": 35,
    "three_quarter_cup_raw_g": 52.5,
    "cooked_cup_g": 140,
    "quarter_cup_cooked_g": 35,
    "half_cup_cooked_g": 70,
    "three_quarter_cup_cooked_g": 105,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mushroom (enoki)",
    "category": "vegetable",
    "subtype": "mushroom",
    "density_confidence": "medium",
    "raw_cup_g": 70,
    "quarter_cup_raw_g": 17.5,
    "half_cup_raw_g": 35,
    "three_quarter_cup_raw_g": 52.5,
    "cooked_cup_g": 140,
    "quarter_cup_cooked_g": 35,
    "half_cup_cooked_g": 70,
    "three_quarter_cup_cooked_g": 105,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mushroom (oyster)",
    "category": "vegetable",
    "subtype": "mushroom",
    "density_confidence": "medium",
    "raw_cup_g": 70,
    "quarter_cup_raw_g": 17.5,
    "half_cup_raw_g": 35,
    "three_quarter_cup_raw_g": 52.5,
    "cooked_cup_g": 140,
    "quarter_cup_cooked_g": 35,
    "half_cup_cooked_g": 70,
    "three_quarter_cup_cooked_g": 105,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mushroom (portobello)",
    "category": "vegetable",
    "subtype": "mushroom",
    "density_confidence": "medium",
    "raw_cup_g": 70,
    "quarter_cup_raw_g": 17.5,
    "half_cup_raw_g": 35,
    "three_quarter_cup_raw_g": 52.5,
    "cooked_cup_g": 140,
    "quarter_cup_cooked_g": 35,
    "half_cup_cooked_g": 70,
    "three_quarter_cup_cooked_g": 105,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mushroom (shiitake)",
    "category": "vegetable",
    "subtype": "mushroom",
    "density_confidence": "medium",
    "raw_cup_g": 70,
    "quarter_cup_raw_g": 17.5,
    "half_cup_raw_g": 35,
    "three_quarter_cup_raw_g": 52.5,
    "cooked_cup_g": 140,
    "quarter_cup_cooked_g": 35,
    "half_cup_cooked_g": 70,
    "three_quarter_cup_cooked_g": 105,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Mustard greens",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Napa cabbage",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Nori (seaweed)",
    "category": "vegetable",
    "subtype": "sea_veg",
    "density_confidence": "low",
    "raw_cup_g": 50,
    "quarter_cup_raw_g": 12.5,
    "half_cup_raw_g": 25,
    "three_quarter_cup_raw_g": 37.5,
    "cooked_cup_g": 100,
    "quarter_cup_cooked_g": 25,
    "half_cup_cooked_g": 50,
    "three_quarter_cup_cooked_g": 75,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Okra",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Onion",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": 110,
    "piece_medium_g": 150,
    "piece_large_g": 200
  },
  {
    "food": "Parsley",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Parsnip",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 130,
    "piece_medium_g": 180,
    "piece_large_g": 240
  },
  {
    "food": "Peas (green)",
    "category": "vegetable",
    "subtype": "legume_green",
    "density_confidence": "high",
    "raw_cup_g": 100,
    "quarter_cup_raw_g": 25,
    "half_cup_raw_g": 50,
    "three_quarter_cup_raw_g": 75,
    "cooked_cup_g": 135,
    "quarter_cup_cooked_g": 33.8,
    "half_cup_cooked_g": 67.5,
    "three_quarter_cup_cooked_g": 101.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Potato",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": 120,
    "piece_medium_g": 180,
    "piece_large_g": 260
  },
  {
    "food": "Potato (nightshade)",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Pumpkin",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Radicchio",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Radish",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 10,
    "piece_medium_g": 15,
    "piece_large_g": 25
  },
  {
    "food": "Red cabbage",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Red onion",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": 120,
    "piece_medium_g": 160,
    "piece_large_g": 210
  },
  {
    "food": "Rocket / Arugula",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Romaine lettuce",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Savoy cabbage",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Shallot",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Silverbeet / Swiss chard",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Snake gourd",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Snow peas",
    "category": "vegetable",
    "subtype": "legume_green",
    "density_confidence": "high",
    "raw_cup_g": 100,
    "quarter_cup_raw_g": 25,
    "half_cup_raw_g": 50,
    "three_quarter_cup_raw_g": 75,
    "cooked_cup_g": 135,
    "quarter_cup_cooked_g": 33.8,
    "half_cup_cooked_g": 67.5,
    "three_quarter_cup_cooked_g": 101.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Spaghetti squash",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Spinach",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Spring onion / scallion",
    "category": "vegetable",
    "subtype": "allium",
    "density_confidence": "high",
    "raw_cup_g": 155,
    "quarter_cup_raw_g": 38.8,
    "half_cup_raw_g": 77.5,
    "three_quarter_cup_raw_g": 116.2,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Sugar snap peas",
    "category": "vegetable",
    "subtype": "legume_green",
    "density_confidence": "high",
    "raw_cup_g": 100,
    "quarter_cup_raw_g": 25,
    "half_cup_raw_g": 50,
    "three_quarter_cup_raw_g": 75,
    "cooked_cup_g": 135,
    "quarter_cup_cooked_g": 33.8,
    "half_cup_cooked_g": 67.5,
    "three_quarter_cup_cooked_g": 101.2,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Swede / rutabaga",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Sweet potato",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": 150,
    "piece_medium_g": 220,
    "piece_large_g": 300
  },
  {
    "food": "Taro",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Tomatillo",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Tomato",
    "category": "vegetable",
    "subtype": "nightshade",
    "density_confidence": "high",
    "raw_cup_g": 160,
    "quarter_cup_raw_g": 40,
    "half_cup_raw_g": 80,
    "three_quarter_cup_raw_g": 120,
    "cooked_cup_g": 190,
    "quarter_cup_cooked_g": 47.5,
    "half_cup_cooked_g": 95,
    "three_quarter_cup_cooked_g": 142.5,
    "piece_small_g": 90,
    "piece_medium_g": 120,
    "piece_large_g": 160
  },
  {
    "food": "Turmeric root",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Turnip",
    "category": "vegetable",
    "subtype": "root_nonstarchy",
    "density_confidence": "medium",
    "raw_cup_g": 130,
    "quarter_cup_raw_g": 32.5,
    "half_cup_raw_g": 65,
    "three_quarter_cup_raw_g": 97.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": 180,
    "piece_medium_g": 260,
    "piece_large_g": 350
  },
  {
    "food": "Turnip greens",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Wakame (seaweed)",
    "category": "vegetable",
    "subtype": "sea_veg",
    "density_confidence": "low",
    "raw_cup_g": 50,
    "quarter_cup_raw_g": 12.5,
    "half_cup_raw_g": 25,
    "three_quarter_cup_raw_g": 37.5,
    "cooked_cup_g": 100,
    "quarter_cup_cooked_g": 25,
    "half_cup_cooked_g": 50,
    "three_quarter_cup_cooked_g": 75,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Water chestnut",
    "category": "vegetable",
    "subtype": "veg_other",
    "density_confidence": "low",
    "raw_cup_g": 120,
    "quarter_cup_raw_g": 30,
    "half_cup_raw_g": 60,
    "three_quarter_cup_raw_g": 90,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Watercress",
    "category": "vegetable",
    "subtype": "leafy",
    "density_confidence": "high",
    "raw_cup_g": 30,
    "quarter_cup_raw_g": 7.5,
    "half_cup_raw_g": 15,
    "three_quarter_cup_raw_g": 22.5,
    "cooked_cup_g": 180,
    "quarter_cup_cooked_g": 45,
    "half_cup_cooked_g": 90,
    "three_quarter_cup_cooked_g": 135,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Yam",
    "category": "vegetable",
    "subtype": "root_starchy",
    "density_confidence": "high",
    "raw_cup_g": 150,
    "quarter_cup_raw_g": 37.5,
    "half_cup_raw_g": 75,
    "three_quarter_cup_raw_g": 112.5,
    "cooked_cup_g": 210,
    "quarter_cup_cooked_g": 52.5,
    "half_cup_cooked_g": 105,
    "three_quarter_cup_cooked_g": 157.5,
    "piece_small_g": null,
    "piece_medium_g": null,
    "piece_large_g": null
  },
  {
    "food": "Zucchini",
    "category": "vegetable",
    "subtype": "gourd",
    "density_confidence": "medium",
    "raw_cup_g": 115,
    "quarter_cup_raw_g": 28.8,
    "half_cup_raw_g": 57.5,
    "three_quarter_cup_raw_g": 86.2,
    "cooked_cup_g": 160,
    "quarter_cup_cooked_g": 40,
    "half_cup_cooked_g": 80,
    "three_quarter_cup_cooked_g": 120,
    "piece_small_g": 120,
    "piece_medium_g": 180,
    "piece_large_g": 250
  }
];
