export type PractitionerOutreachSeedEntry = {
  practiceName: string
  name?: string
  email?: string
  country: string
  category: string
  subcategory: string
  region?: string
  city?: string
  practitionerType?: string
  website?: string
  emailType?: string
  sourceUrl?: string
  relevanceNotes?: string
  safetyBasis?: string
  doNotContactNotice?: boolean
  status?: string
}

const publicContactSafety =
  'Public practice contact page; general clinic/business contact only; keep NOT_REVIEWED until owner reviews.'

export const practitionerOutreachSeed: PractitionerOutreachSeedEntry[] = [
  {
    practiceName: 'CityMed Clinic',
    name: 'Clinic team',
    email: 'info@citymed.com.au',
    country: 'Australia',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Victoria',
    city: 'South Melbourne',
    practitionerType: 'General practice clinic',
    website: 'https://www.citymed.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.citymed.com.au/contact/',
    relevanceNotes: 'Mixed billing medical practice with GP services and public clinic contact details.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Bowral Physiotherapy',
    name: 'Clinic team',
    email: 'admin@bowralphysiotherapy.com.au',
    country: 'Australia',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Bowral',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.bowralphysiotherapy.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.bowralphysiotherapy.com.au/contact-us',
    relevanceNotes: 'Physiotherapy clinic with public admin contact details.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Outlook Psychology',
    name: 'Clinic team',
    email: 'admin@opgove.com.au',
    country: 'Australia',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Psychology clinic',
    website: 'https://www.outlookpsychology.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.outlookpsychology.com.au/contact',
    relevanceNotes: 'Psychology service offering telehealth support for regional, rural, and remote Australia.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: "Men's Health Clinic",
    name: 'Clinic support',
    email: 'info@mhc.com.au',
    country: 'Australia',
    category: "Men's Health",
    subcategory: 'Hormone / Testosterone Clinic',
    region: 'New South Wales',
    city: 'Crows Nest',
    practitionerType: "Men's health clinic",
    website: 'https://menshealthclinic.com/au/',
    emailType: 'clinic',
    sourceUrl: 'https://menshealthclinic.com/au/contact-us',
    relevanceNotes: "Men's health clinic with Australia-wide doctor network and public clinic support email.",
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Adaptive Chiropractic CBD',
    name: 'Clinic team',
    email: 'care@adaptchiro.com.au',
    country: 'Australia',
    category: 'Musculoskeletal & Pain',
    subcategory: 'Spinal / Back Pain Clinic',
    region: 'Victoria',
    city: 'Melbourne',
    practitionerType: 'Chiropractic clinic',
    website: 'https://www.melbournecbdchiro.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.melbournecbdchiro.com.au/contact/',
    relevanceNotes: 'Chiropractic clinic listing back pain, neck pain, posture, and sciatica support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Anchorpoint Support Coordination',
    name: 'Support team',
    email: 'hello@anchorpoint.net.au',
    country: 'Australia',
    category: 'Rehab & Disability Support',
    subcategory: 'Disability Support Provider',
    region: 'Western Australia',
    city: 'Perth',
    practitionerType: 'NDIS support coordination provider',
    website: 'https://www.anchorpoint.net.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.anchorpoint.net.au/contact',
    relevanceNotes: 'NDIS registered provider delivering support coordination across Western Australia.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Metabolic Health Nutrition',
    name: 'Clinic team',
    email: 'info@metabolichealthnutrition.com.au',
    country: 'Australia',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.metabolichealthnutrition.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.metabolichealthnutrition.com.au/contact',
    relevanceNotes: 'Metabolic health dietitian service offering Australia-wide telehealth.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Humble Naturopathics',
    name: 'Clinic team',
    email: 'hello@humblenaturopathics.com.au',
    country: 'Australia',
    category: 'Holistic & Integrative',
    subcategory: 'Naturopath',
    region: 'Victoria',
    city: 'Mildura',
    practitionerType: 'Naturopathic clinic',
    website: 'https://www.humblenaturopathics.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.humblenaturopathics.com.au/contact',
    relevanceNotes: 'Holistic health clinic with naturopathic consultations and Australia-wide telehealth.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Apple Dental',
    name: 'Clinic team',
    email: 'info@apple-dental.com.au',
    country: 'Australia',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'Queensland',
    city: 'Newstead',
    practitionerType: 'Dental clinic',
    website: 'https://www.apple-dental.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.apple-dental.com.au/contact-apple-dental',
    relevanceNotes: 'Dental clinic with general, preventive, children, cosmetic, and denture services.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'OptimEyes Optometry',
    name: 'Clinic team',
    email: 'info@optimeyes.com.au',
    country: 'Australia',
    category: 'Eye & Hearing',
    subcategory: 'Optometrist',
    region: 'New South Wales',
    city: 'Frenchs Forest',
    practitionerType: 'Optometry clinic',
    website: 'https://www.optimeyes.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.optimeyes.com.au/contact/',
    relevanceNotes: 'Optometry clinic with public contact details and eye-care services.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: "St Vincent's Pathology",
    name: 'Business development team',
    email: 'pathologyBD@svha.org.au',
    country: 'Australia',
    category: 'Diagnostics & Testing',
    subcategory: 'Pathology / Lab Testing',
    region: 'Victoria',
    city: 'Fitzroy',
    practitionerType: 'Pathology service',
    website: 'https://path.svhm.org.au',
    emailType: 'admin',
    sourceUrl: 'https://path.svhm.org.au/contact',
    relevanceNotes: 'Pathology service with public pathology business development contact.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Keperra Compounding Pharmacy',
    name: 'Pharmacy team',
    email: 'info@compoundingpharmacy.com.au',
    country: 'Australia',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'Queensland',
    city: 'Keperra',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.compoundingpharmacy.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.compoundingpharmacy.com.au/contact-compounding-pharmacy',
    relevanceNotes: 'Compounding pharmacy with practitioner services and Australia-wide compounding support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'JJ Mobile Physio',
    name: 'Clinic team',
    email: 'info@JJMobilePhysio.com.au',
    country: 'Australia',
    category: 'Aged Care & Home Care',
    subcategory: 'Mobile Physio',
    region: 'Victoria',
    city: 'Melbourne',
    practitionerType: 'Mobile physiotherapy service',
    website: 'https://jjmobilephysio.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://jjmobilephysio.com.au/contact',
    relevanceNotes: 'Mobile physiotherapy provider for home, aged care, and NDIS support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
]
