export type PractitionerOutreachSeedEntry = {
  practiceName: string
  name?: string
  email?: string
  country: string
  category: string
  subcategory: string
  region?: string
  city?: string
  practitionerType?: string
  phone?: string
  website?: string
  emailType?: string
  sourceUrl?: string
  relevanceNotes?: string
  safetyBasis?: string
  doNotContactNotice?: boolean
  status?: string
}

const publicContactSafety =
  'Public clinic/source page; general clinic/business contact only; keep NOT_REVIEWED until owner reviews.'

type PublicPracticeContactInput = Omit<PractitionerOutreachSeedEntry, 'country' | 'safetyBasis' | 'status'>

type BulkContactRow = readonly [
  practiceName: string,
  email: string,
  subcategory: string,
  region: string,
  city: string,
  practitionerType: string,
  website: string,
  sourceUrl: string,
  relevanceNotes?: string,
]

function publicPracticeContact(entry: PublicPracticeContactInput): PractitionerOutreachSeedEntry {
  return {
    name: 'Clinic team',
    emailType: 'clinic',
    ...entry,
    country: 'Australia',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  }
}

function categoryPracticeContacts(category: string, rows: BulkContactRow[]): PractitionerOutreachSeedEntry[] {
  return rows.map(([practiceName, email, subcategory, region, city, practitionerType, website, sourceUrl, relevanceNotes]) =>
    publicPracticeContact({
      practiceName,
      email,
      category,
      subcategory,
      region,
      city,
      practitionerType,
      website,
      sourceUrl,
      relevanceNotes: relevanceNotes || `${practitionerType} with public contact email.`,
    }),
  )
}

export const practitionerOutreachSeed: PractitionerOutreachSeedEntry[] = [
  {
    practiceName: 'CityMed Clinic',
    name: 'Clinic team',
    email: 'info@citymed.com.au',
    country: 'Australia',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Victoria',
    city: 'South Melbourne',
    practitionerType: 'General practice clinic',
    website: 'https://www.citymed.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.citymed.com.au/contact/',
    relevanceNotes: 'Mixed billing medical practice with GP services and public clinic contact details.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Bowral Physiotherapy',
    name: 'Clinic team',
    email: 'admin@bowralphysiotherapy.com.au',
    country: 'Australia',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Bowral',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.bowralphysiotherapy.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.bowralphysiotherapy.com.au/contact-us',
    relevanceNotes: 'Physiotherapy clinic with public admin contact details.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Outlook Psychology',
    name: 'Clinic team',
    email: 'admin@opgove.com.au',
    country: 'Australia',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Psychology clinic',
    website: 'https://www.outlookpsychology.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.outlookpsychology.com.au/contact',
    relevanceNotes: 'Psychology service offering telehealth support for regional, rural, and remote Australia.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: "Men's Health Clinic",
    name: 'Clinic support',
    email: 'info@mhc.com.au',
    country: 'Australia',
    category: "Men's Health",
    subcategory: 'Hormone / Testosterone Clinic',
    region: 'New South Wales',
    city: 'Crows Nest',
    practitionerType: "Men's health clinic",
    website: 'https://menshealthclinic.com/au/',
    emailType: 'clinic',
    sourceUrl: 'https://menshealthclinic.com/au/contact-us',
    relevanceNotes: "Men's health clinic with Australia-wide doctor network and public clinic support email.",
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Adaptive Chiropractic CBD',
    name: 'Clinic team',
    email: 'care@adaptchiro.com.au',
    country: 'Australia',
    category: 'Musculoskeletal & Pain',
    subcategory: 'Spinal / Back Pain Clinic',
    region: 'Victoria',
    city: 'Melbourne',
    practitionerType: 'Chiropractic clinic',
    website: 'https://www.melbournecbdchiro.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.melbournecbdchiro.com.au/contact/',
    relevanceNotes: 'Chiropractic clinic listing back pain, neck pain, posture, and sciatica support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Anchorpoint Support Coordination',
    name: 'Support team',
    email: 'hello@anchorpoint.net.au',
    country: 'Australia',
    category: 'Rehab & Disability Support',
    subcategory: 'Disability Support Provider',
    region: 'Western Australia',
    city: 'Perth',
    practitionerType: 'NDIS support coordination provider',
    website: 'https://www.anchorpoint.net.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.anchorpoint.net.au/contact',
    relevanceNotes: 'NDIS registered provider delivering support coordination across Western Australia.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Metabolic Health Nutrition',
    name: 'Clinic team',
    email: 'info@metabolichealthnutrition.com.au',
    country: 'Australia',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.metabolichealthnutrition.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.metabolichealthnutrition.com.au/contact',
    relevanceNotes: 'Metabolic health dietitian service offering Australia-wide telehealth.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Humble Naturopathics',
    name: 'Clinic team',
    email: 'hello@humblenaturopathics.com.au',
    country: 'Australia',
    category: 'Holistic & Integrative',
    subcategory: 'Naturopath',
    region: 'Victoria',
    city: 'Mildura',
    practitionerType: 'Naturopathic clinic',
    website: 'https://www.humblenaturopathics.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.humblenaturopathics.com.au/contact',
    relevanceNotes: 'Holistic health clinic with naturopathic consultations and Australia-wide telehealth.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Apple Dental',
    name: 'Clinic team',
    email: 'info@apple-dental.com.au',
    country: 'Australia',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'Queensland',
    city: 'Newstead',
    practitionerType: 'Dental clinic',
    website: 'https://www.apple-dental.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.apple-dental.com.au/contact-apple-dental',
    relevanceNotes: 'Dental clinic with general, preventive, children, cosmetic, and denture services.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'OptimEyes Optometry',
    name: 'Clinic team',
    email: 'info@optimeyes.com.au',
    country: 'Australia',
    category: 'Eye & Hearing',
    subcategory: 'Optometrist',
    region: 'New South Wales',
    city: 'Frenchs Forest',
    practitionerType: 'Optometry clinic',
    website: 'https://www.optimeyes.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.optimeyes.com.au/contact/',
    relevanceNotes: 'Optometry clinic with public contact details and eye-care services.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: "St Vincent's Pathology",
    name: 'Business development team',
    email: 'pathologyBD@svha.org.au',
    country: 'Australia',
    category: 'Diagnostics & Testing',
    subcategory: 'Pathology / Lab Testing',
    region: 'Victoria',
    city: 'Fitzroy',
    practitionerType: 'Pathology service',
    website: 'https://path.svhm.org.au',
    emailType: 'admin',
    sourceUrl: 'https://path.svhm.org.au/contact',
    relevanceNotes: 'Pathology service with public pathology business development contact.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'Keperra Compounding Pharmacy',
    name: 'Pharmacy team',
    email: 'info@compoundingpharmacy.com.au',
    country: 'Australia',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'Queensland',
    city: 'Keperra',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.compoundingpharmacy.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://www.compoundingpharmacy.com.au/contact-compounding-pharmacy',
    relevanceNotes: 'Compounding pharmacy with practitioner services and Australia-wide compounding support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  {
    practiceName: 'JJ Mobile Physio',
    name: 'Clinic team',
    email: 'info@JJMobilePhysio.com.au',
    country: 'Australia',
    category: 'Aged Care & Home Care',
    subcategory: 'Mobile Physio',
    region: 'Victoria',
    city: 'Melbourne',
    practitionerType: 'Mobile physiotherapy service',
    website: 'https://jjmobilephysio.com.au',
    emailType: 'clinic',
    sourceUrl: 'https://jjmobilephysio.com.au/contact',
    relevanceNotes: 'Mobile physiotherapy provider for home, aged care, and NDIS support.',
    safetyBasis: publicContactSafety,
    status: 'NOT_REVIEWED',
  },
  publicPracticeContact({
    practiceName: 'The Doctors Mulgrave Road Medical Centre',
    email: 'admin@mulgraveroad.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Queensland',
    city: 'Cairns',
    practitionerType: 'General practice clinic',
    website: 'https://www.mulgraveroad.com.au',
    sourceUrl: 'https://www.mulgraveroad.com.au/contact/',
    relevanceNotes: 'General practice clinic with public admin email on contact page.',
  }),
  publicPracticeContact({
    practiceName: 'Moama Health Clinic',
    email: 'info@moamahealthclinic.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'New South Wales',
    city: 'Moama',
    practitionerType: 'Medical clinic',
    website: 'https://www.moamahealthclinic.com.au',
    sourceUrl: 'https://www.moamahealthclinic.com.au/',
    relevanceNotes: 'General medical clinic with public email and phone details.',
  }),
  publicPracticeContact({
    practiceName: 'Mill Park Family Medical Centre',
    email: 'reception@mpfmc.com.au',
    category: 'GPs & Doctors',
    subcategory: 'Family Doctor',
    region: 'Victoria',
    city: 'Mill Park',
    practitionerType: 'Family medical centre',
    website: 'https://mpfmc.com.au',
    sourceUrl: 'https://mpfmc.com.au/contact-us/',
    relevanceNotes: 'Family medical centre with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Iluka Medical Centre',
    email: 'reception@ilukamedical.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Western Australia',
    city: 'Iluka',
    practitionerType: 'GP clinic',
    website: 'https://www.ilukamedical.com.au',
    sourceUrl: 'https://www.ilukamedical.com.au/contact-us/',
    relevanceNotes: 'GP clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Canterbury Medical Clinic',
    email: 'reception@canterburymedical.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Victoria',
    city: 'Canterbury',
    practitionerType: 'Medical clinic',
    website: 'https://canterburymedicalclinic.com.au',
    sourceUrl: 'https://canterburymedicalclinic.com.au/contact-us/',
    relevanceNotes: 'Medical clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Highton Village Medical Clinic',
    email: 'reception@hightonmedical.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Victoria',
    city: 'Highton',
    practitionerType: 'General practice clinic',
    website: 'https://www.hightonmedical.com.au',
    sourceUrl: 'https://www.hightonmedical.com.au/contact',
    relevanceNotes: 'General practice clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Alkimos Medical Centre',
    email: 'info@alkimosmedical.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Western Australia',
    city: 'Alkimos',
    practitionerType: 'Medical centre',
    website: 'https://alkimosmedical.com.au',
    sourceUrl: 'https://alkimosmedical.com.au/contact/',
    relevanceNotes: 'Medical centre with public general email.',
  }),
  publicPracticeContact({
    practiceName: 'Buderim Medical Centre',
    email: 'info@buderimmedical.com.au',
    category: 'GPs & Doctors',
    subcategory: 'General Practitioner (GP)',
    region: 'Queensland',
    city: 'Buderim',
    practitionerType: 'GP clinic',
    website: 'https://buderimmedical.com.au',
    sourceUrl: 'https://buderimmedical.com.au/contact-us/',
    relevanceNotes: 'GP clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Cosmedicentre',
    email: 'info@cosmedicentre.com',
    category: 'GPs & Doctors',
    subcategory: 'Ophthalmologist',
    region: 'New South Wales',
    city: 'Coffs Harbour',
    practitionerType: 'Specialist medical clinic',
    website: 'https://www.cosmedicentre.com.au',
    sourceUrl: 'https://www.cosmedicentre.com.au/contact',
    relevanceNotes: 'Specialist ophthalmology-led medical clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Physiotherapy Clinic',
    email: 'info@physiotherapyclinic.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Randwick',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.physiotherapyclinic.com.au',
    sourceUrl: 'https://www.physiotherapyclinic.com.au/contact',
    relevanceNotes: 'Physiotherapy clinic with public general email.',
  }),
  publicPracticeContact({
    practiceName: 'Burnside Physiotherapy',
    email: 'admin@burnsidephysio.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'South Australia',
    city: 'Hazelwood Park',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://burnsidephysiotherapy.com.au',
    sourceUrl: 'https://burnsidephysiotherapy.com.au/contact/',
    relevanceNotes: 'Physiotherapy clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Beaumaris Physiotherapy Centre',
    email: 'info@beaumarisphysio.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'Victoria',
    city: 'Beaumaris',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.beaumarisphysio.com.au',
    sourceUrl: 'https://www.beaumarisphysio.com.au/contact/',
    relevanceNotes: 'Physiotherapy clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'In Balance Physio Clinic',
    email: 'admin@ibphysio.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Manly',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.ibphysio.com.au',
    sourceUrl: 'https://www.ibphysio.com.au/contact-us/',
    relevanceNotes: 'Physiotherapy clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Coastal Movement Physiotherapy',
    email: 'admin@coastalmovementphysiotherapy.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Budgewoi',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.coastalmovementphysiotherapy.com.au',
    sourceUrl: 'https://www.coastalmovementphysiotherapy.com.au/contact',
    relevanceNotes: 'Physiotherapy clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Edgecliff Physiotherapy',
    email: 'info@edgecliffphysio.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Edgecliff',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.edgecliffphysio.com.au',
    sourceUrl: 'https://www.edgecliffphysio.com.au/contact-us/',
    relevanceNotes: 'Physiotherapy clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Physio Pro Perth',
    email: 'floreatphysio@physioproperth.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'Western Australia',
    city: 'Floreat',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.physioproperth.com.au',
    sourceUrl: 'https://www.physioproperth.com.au/contact/',
    relevanceNotes: 'Physiotherapy clinic with public clinic email.',
  }),
  publicPracticeContact({
    practiceName: 'Phyx You Physiotherapy and Rehabilitation',
    email: 'info@phyxyou.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'Port Macquarie',
    practitionerType: 'Physiotherapy and rehabilitation clinic',
    website: 'https://www.phyxyou.com.au',
    sourceUrl: 'https://www.phyxyou.com.au/contact/',
    relevanceNotes: 'Physiotherapy and rehabilitation clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Belmont City Physiotherapy',
    email: 'info@belmontcityphysio.com.au',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'Western Australia',
    city: 'Belmont',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.belmontcityphysio.com.au',
    sourceUrl: 'https://www.belmontcityphysio.com.au/contact',
    relevanceNotes: 'Physiotherapy clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Ryde Physiotherapy Centre',
    email: 'rydephysiotherapycentre@gmail.com',
    category: 'Allied Health',
    subcategory: 'Physiotherapist',
    region: 'New South Wales',
    city: 'North Ryde',
    practitionerType: 'Physiotherapy clinic',
    website: 'https://www.rydephysiotherapycentre.com.au',
    sourceUrl: 'https://www.rydephysiotherapycentre.com.au/contact-us',
    relevanceNotes: 'Physiotherapy clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Austral Podiatry',
    email: 'info@australpodiatry.com.au',
    category: 'Allied Health',
    subcategory: 'Podiatrist',
    region: 'New South Wales',
    city: 'Austral',
    practitionerType: 'Podiatry clinic',
    website: 'https://www.australpodiatry.com.au',
    sourceUrl: 'https://www.australpodiatry.com.au/contact',
    relevanceNotes: 'Podiatry clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Bayside Sports Podiatry',
    email: 'admin@baysidesportspodiatry.com.au',
    category: 'Allied Health',
    subcategory: 'Podiatrist',
    region: 'Victoria',
    city: 'Sandringham',
    practitionerType: 'Sports podiatry clinic',
    website: 'https://www.baysidesportspodiatry.com.au',
    sourceUrl: 'https://www.baysidesportspodiatry.com.au/contact',
    relevanceNotes: 'Sports podiatry clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Australian Psychology & Wellness Centre',
    email: 'info@apawc.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'New South Wales',
    city: 'Coffs Harbour',
    practitionerType: 'Psychology clinic',
    website: 'https://www.apawc.com.au',
    sourceUrl: 'https://www.apawc.com.au/contactus/',
    relevanceNotes: 'Psychology and wellness clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Ashley Depasquale Psychology',
    email: 'contact@adpsychology.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Victoria',
    city: 'Prahran',
    practitionerType: 'Psychology practice',
    website: 'https://www.adpsychology.com.au',
    sourceUrl: 'https://www.adpsychology.com.au/contact',
    relevanceNotes: 'Psychology practice with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Connectedness Psychology and Coaching',
    email: 'admin@connectedness.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Queensland',
    city: 'Townsville',
    practitionerType: 'Psychology and coaching clinic',
    website: 'https://www.connectedness.com.au',
    sourceUrl: 'https://www.connectedness.com.au/contact',
    relevanceNotes: 'Psychology clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Blue Door Psychology',
    email: 'reception@bluedoorpsychology.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'South Australia',
    city: "O'Halloran Hill",
    practitionerType: 'Psychology clinic',
    website: 'https://www.bluedoorpsychology.com.au',
    sourceUrl: 'https://www.bluedoorpsychology.com.au/contact-us',
    relevanceNotes: 'Psychology clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'MBH Psychology',
    email: 'info@mbhpsychology.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Victoria',
    city: 'Hawthorn',
    practitionerType: 'Psychology practice',
    website: 'https://www.mbhpsychology.com.au',
    sourceUrl: 'https://www.mbhpsychology.com.au/contact',
    relevanceNotes: 'Psychology practice with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Macquarie Psychology',
    email: 'admin@macquariepsychology.net.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Tasmania',
    city: 'Hobart',
    practitionerType: 'Psychology clinic',
    website: 'https://www.macquariepsychology.net.au',
    sourceUrl: 'https://www.macquariepsychology.net.au/contact/',
    relevanceNotes: 'Psychology clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'University of Melbourne Psychology Clinic',
    email: 'clinic-psych@unimelb.edu.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Victoria',
    city: 'Carlton',
    practitionerType: 'Psychology clinic',
    website: 'https://psychology.mthc.com.au',
    sourceUrl: 'https://psychology.mthc.com.au/contact/',
    relevanceNotes: 'University psychology clinic with public clinic email.',
  }),
  publicPracticeContact({
    practiceName: 'Bridges Psychology Clinic',
    email: 'info@bridgespsychology.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'New South Wales',
    city: 'Burwood',
    practitionerType: 'Psychology clinic',
    website: 'https://bridgespsychologyclinic.com.au',
    sourceUrl: 'https://bridgespsychologyclinic.com.au/contact-us/',
    relevanceNotes: 'Psychology clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'CT Psychology',
    email: 'admin@ctpsychology.com.au',
    category: 'Mental Health',
    subcategory: 'Psychologist',
    region: 'Victoria',
    city: 'East Melbourne',
    practitionerType: 'Psychology practice',
    website: 'https://ctpsychology.com.au',
    sourceUrl: 'https://ctpsychology.com.au/contact-us/',
    relevanceNotes: 'Psychology practice with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Penrith Chiropractor Clinic',
    email: 'info@penrithchiro.com.au',
    category: 'Musculoskeletal & Pain',
    subcategory: 'Spinal / Back Pain Clinic',
    region: 'New South Wales',
    city: 'South Penrith',
    practitionerType: 'Chiropractic clinic',
    website: 'https://penrithchiro.com.au',
    sourceUrl: 'https://penrithchiro.com.au/contact-us/',
    relevanceNotes: 'Chiropractic clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Naturally Balanced Chiropractic',
    email: 'info@natbalchiro.com.au',
    category: 'Musculoskeletal & Pain',
    subcategory: 'Spinal / Back Pain Clinic',
    region: 'New South Wales',
    city: 'Russell Lea',
    practitionerType: 'Chiropractic clinic',
    website: 'https://natbalchiro.com.au',
    sourceUrl: 'https://natbalchiro.com.au/contact-us-3/',
    relevanceNotes: 'Chiropractic clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'My EP Exercise Physiology',
    email: 'info@myep.com.au',
    category: 'Allied Health',
    subcategory: 'Exercise Physiologist',
    region: 'Queensland',
    city: 'Sunshine Coast',
    practitionerType: 'Exercise physiology clinic',
    website: 'https://www.myep.com.au',
    sourceUrl: 'https://www.myep.com.au/contact-us',
    relevanceNotes: 'Exercise physiology clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'My Exercise Physiology',
    email: 'phil@myexercisephysiology.au',
    category: 'Allied Health',
    subcategory: 'Exercise Physiologist',
    region: 'Victoria',
    city: 'The Basin',
    practitionerType: 'Exercise physiology service',
    website: 'https://www.myexercisephysiology.au',
    sourceUrl: 'https://www.myexercisephysiology.au/contact',
    relevanceNotes: 'Exercise physiology service with public email.',
  }),
  publicPracticeContact({
    practiceName: 'Access Exercise Physiology',
    email: 'enquiries@accessexercisephysiology.com.au',
    category: 'Allied Health',
    subcategory: 'Exercise Physiologist',
    region: 'Western Australia',
    city: 'Perth',
    practitionerType: 'Mobile exercise physiology service',
    website: 'https://www.accessexercisephysiology.com.au',
    sourceUrl: 'https://www.accessexercisephysiology.com.au/uploads/1/2/3/9/123990609/form-_referral_information_for_your_gp.pdf',
    relevanceNotes: 'Mobile exercise physiology service with public referral email.',
  }),
  publicPracticeContact({
    practiceName: 'Achieve Exercise Physiologists',
    email: 'info@achieveexercise.com.au',
    category: 'Allied Health',
    subcategory: 'Exercise Physiologist',
    region: 'Australia',
    city: 'Australia-wide',
    practitionerType: 'Exercise physiology service',
    website: 'https://achieveexercise.com.au',
    sourceUrl: 'https://achieveexercise.com.au/wp-content/uploads/2021/08/Achieve-EP-Referral-Form_2021.pdf',
    relevanceNotes: 'Exercise physiology provider with public referral email.',
  }),
  publicPracticeContact({
    practiceName: 'Diala Murr Dietary Clinic',
    email: 'info@dmdietaryclinic.com',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Victoria',
    city: 'Coburg North',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.dmdietaryclinic.com',
    sourceUrl: 'https://www.dmdietaryclinic.com/',
    relevanceNotes: 'Accredited practising dietitian clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Well Woman Dietetics',
    email: 'hello@wellwomandietetics.com.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.wellwomandietetics.com.au',
    sourceUrl: 'https://www.wellwomandietetics.com.au/',
    relevanceNotes: 'Australia-wide fertility and prenatal dietitian service with public email.',
  }),
  publicPracticeContact({
    practiceName: 'Complete Dietetics',
    email: 'admin@completedietetics.com',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Victoria',
    city: 'Geelong',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.completedietetics.com.au',
    sourceUrl: 'https://www.completedietetics.com.au/contact-us-1',
    relevanceNotes: 'Dietitian clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Your Nutrition',
    email: 'hello@yournutrition.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Victoria',
    city: 'Newport',
    practitionerType: 'Dietitian service',
    website: 'https://www.yournutrition.au',
    sourceUrl: 'https://www.yournutrition.au/contact',
    relevanceNotes: 'Dietitian service with public business email.',
  }),
  publicPracticeContact({
    practiceName: 'Helen Barnett Dietitian',
    email: 'admin@helenbarnett.com.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'New South Wales',
    city: 'Orange',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.helenbarnett.com.au',
    sourceUrl: 'https://www.helenbarnett.com.au/contact-2/',
    relevanceNotes: 'Dietitian clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'My Dietitian Clinic',
    email: 'contact@mydietitianclinic.com',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Queensland',
    city: 'Mermaid Waters',
    practitionerType: 'Dietitian clinic',
    website: 'https://mydietitianclinic.com',
    sourceUrl: 'https://mydietitianclinic.com/contact/',
    relevanceNotes: 'Dietitian clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Nutrition Solutions',
    email: 'info@nutrition-solutions.com.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Queensland',
    city: 'Yeronga',
    practitionerType: 'Nutrition and dietetic clinic',
    website: 'https://nutrition-solutions.com.au',
    sourceUrl: 'https://nutrition-solutions.com.au/contact/',
    relevanceNotes: 'Dietetic clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Verdant Nutrition',
    email: 'hello@verdantnutrition.com.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Australia-wide',
    city: 'Telehealth',
    practitionerType: 'Nutrition clinic',
    website: 'https://www.verdantnutrition.com.au',
    sourceUrl: 'https://www.verdantnutrition.com.au/contact',
    relevanceNotes: 'Plant-based nutrition clinic with public hello email.',
  }),
  publicPracticeContact({
    practiceName: 'Nutrition Solutions Victoria',
    email: 'info@nutritionsolutionsvictoria.com.au',
    category: 'Nutrition & Metabolic Health',
    subcategory: 'Dietitian',
    region: 'Victoria',
    city: 'Melbourne',
    practitionerType: 'Dietitian clinic',
    website: 'https://www.nutritionsolutionsvictoria.com.au',
    sourceUrl: 'https://www.nutritionsolutionsvictoria.com.au/contact/',
    relevanceNotes: 'Melbourne dietitian clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Nova Holistic Naturopath',
    email: 'novaholisticnaturopath@proton.me',
    category: 'Holistic & Integrative',
    subcategory: 'Naturopath',
    region: 'Queensland',
    city: 'Gold Coast',
    practitionerType: 'Naturopathic service',
    website: 'https://www.novaholisticnaturopath.au',
    sourceUrl: 'https://www.novaholisticnaturopath.au/contact',
    relevanceNotes: 'Naturopathic service with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Lucy Frew Naturopath',
    email: 'lucynaturopath@yahoo.com.au',
    category: 'Holistic & Integrative',
    subcategory: 'Naturopath',
    region: 'New South Wales',
    city: 'Erina',
    practitionerType: 'Naturopathic service',
    website: 'https://www.lucyfrewnaturopath.com.au',
    sourceUrl: 'https://www.lucyfrewnaturopath.com.au/contact',
    relevanceNotes: 'Naturopathic practitioner with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Mill Park Dental',
    email: 'info@millparkdental.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'Victoria',
    city: 'Mill Park',
    practitionerType: 'Dental clinic',
    website: 'https://www.millparkdental.com.au',
    sourceUrl: 'https://www.millparkdental.com.au/contact-us/',
    relevanceNotes: 'Dental clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'QC Dental',
    email: 'reception@qcdental.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'New South Wales',
    city: 'Chatswood',
    practitionerType: 'Dental clinic',
    website: 'https://qcdental.com.au',
    sourceUrl: 'https://qcdental.com.au/contact',
    relevanceNotes: 'Dental clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Mascot Dental Clinic',
    email: 'reception@mascotdentalclinic.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'New South Wales',
    city: 'Mascot',
    practitionerType: 'Dental clinic',
    website: 'https://www.mascotdentalclinic.com.au',
    sourceUrl: 'https://www.mascotdentalclinic.com.au/contact-us.html',
    relevanceNotes: 'Dental clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Highbury Dental Care',
    email: 'highburydental@gmail.com',
    category: 'Dental & Oral Health',
    subcategory: 'Dentist',
    region: 'South Australia',
    city: 'Highbury',
    practitionerType: 'Dental clinic',
    website: 'https://highburydentalcare.com.au',
    sourceUrl: 'https://highburydentalcare.com.au/',
    relevanceNotes: 'Dental clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'MyOrtho',
    email: 'info@myortho.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Orthodontist',
    region: 'New South Wales',
    city: 'Randwick',
    practitionerType: 'Orthodontic clinic',
    website: 'https://www.myortho.com.au',
    sourceUrl: 'https://www.myortho.com.au/',
    relevanceNotes: 'Orthodontic clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Smileworx Orthodontics',
    email: 'reception@smileworx.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Orthodontist',
    region: 'Western Australia',
    city: 'Duncraig',
    practitionerType: 'Orthodontic clinic',
    website: 'https://smileworx.com.au',
    sourceUrl: 'https://smileworx.com.au/contact-us/',
    relevanceNotes: 'Orthodontic clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Brighton Orthodontics',
    email: 'info@brightonorthodontics.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Orthodontist',
    region: 'Victoria',
    city: 'Brighton',
    practitionerType: 'Orthodontic clinic',
    website: 'https://brightonorthodontics.com.au',
    sourceUrl: 'https://brightonorthodontics.com.au/contact-us/',
    relevanceNotes: 'Orthodontic clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'The Orthodontist',
    email: 'admin@the-orthodontist.com.au',
    category: 'Dental & Oral Health',
    subcategory: 'Orthodontist',
    region: 'New South Wales',
    city: 'Gosford',
    practitionerType: 'Orthodontic clinic',
    website: 'https://www.the-orthodontist.com.au',
    sourceUrl: 'https://www.the-orthodontist.com.au/contact',
    relevanceNotes: 'Orthodontic clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Look Of Australia',
    email: 'info@lookofaustralia.com',
    category: 'Eye & Hearing',
    subcategory: 'Optometrist',
    region: 'Tasmania',
    city: 'Hobart',
    practitionerType: 'Optometry clinic',
    website: 'https://www.lookofaustralia.com',
    sourceUrl: 'https://www.lookofaustralia.com/contact',
    relevanceNotes: 'Optometry clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Ears Plus',
    email: 'reception@earsplus.com.au',
    category: 'Eye & Hearing',
    subcategory: 'Audiologist',
    region: 'New South Wales',
    city: 'Burwood',
    practitionerType: 'Audiology clinic',
    website: 'https://earsplus.com.au',
    sourceUrl: 'https://earsplus.com.au/contact',
    relevanceNotes: 'Audiology clinic with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'DWM Audiology',
    email: 'info@dwmaudiology.com.au',
    category: 'Eye & Hearing',
    subcategory: 'Audiologist',
    region: 'Victoria',
    city: 'Heidelberg',
    practitionerType: 'Audiology clinic',
    website: 'https://www.dwmaudiology.com.au',
    sourceUrl: 'https://www.dwmaudiology.com.au/contact/',
    relevanceNotes: 'Audiology clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Spectrum Interventional Radiology',
    email: 'ir@spectrumradiology.com.au',
    category: 'Diagnostics & Testing',
    subcategory: 'Imaging / Radiology (X-ray, CT, MRI, Ultrasound)',
    region: 'New South Wales',
    city: 'Sydney',
    practitionerType: 'Radiology clinic',
    website: 'https://www.spectrumir.com.au',
    sourceUrl: 'https://www.spectrumir.com.au/contact',
    relevanceNotes: 'Radiology clinic with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'The Compounding Pharmacy of Australia',
    email: 'info@tcpa.com.au',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'New South Wales',
    city: 'Mosman',
    practitionerType: 'Compounding pharmacy',
    website: 'https://compoundingpharmacyaustralia.com',
    sourceUrl: 'https://compoundingpharmacyaustralia.com/pages/contact',
    relevanceNotes: 'Compounding pharmacy with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Citymed Compounding Pharmacy',
    email: 'citymedcompounding@gmail.com',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'New South Wales',
    city: 'Sydney',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.citymedpharmacy.com.au',
    sourceUrl: 'https://www.citymedpharmacy.com.au/contact',
    relevanceNotes: 'Compounding pharmacy with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Coastal Compounding Pharmacy',
    email: 'info@coastalcompounding.com.au',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'Victoria',
    city: 'Torquay',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.cottagepharmacy.com.au',
    sourceUrl: 'https://www.cottagepharmacy.com.au/contact-us/coastal-compounding-pharmacy',
    relevanceNotes: 'Compounding pharmacy with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Aussie Pharmacy',
    email: 'support@aussiepharmacy.com.au',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'New South Wales',
    city: 'Sydney',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.aussiepharmacy.com.au',
    sourceUrl: 'https://www.aussiepharmacy.com.au/pages/compounding-pharmacy',
    relevanceNotes: 'Compounding pharmacy service with public support email.',
  }),
  publicPracticeContact({
    practiceName: 'AHS Compounding Pharmacy',
    email: 'info@ahscompounding.com.au',
    category: 'Pharmacy & Medication Support',
    subcategory: 'Compounding Pharmacy',
    region: 'Victoria',
    city: 'Reservoir',
    practitionerType: 'Compounding pharmacy',
    website: 'https://www.ahscompounding.com.au',
    sourceUrl: 'https://www.ahscompounding.com.au/contact',
    relevanceNotes: 'Compounding pharmacy with public lab email.',
  }),
  publicPracticeContact({
    practiceName: 'Tel Speech Pathology',
    email: 'admin@telspeechpathology.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'South Australia',
    city: 'Christies Beach',
    practitionerType: 'Speech pathology clinic',
    website: 'https://www.telspeechpathology.com.au',
    sourceUrl: 'https://www.telspeechpathology.com.au/contact',
    relevanceNotes: 'Speech pathology clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'Bullseye Speech Pathology',
    email: 'info@bullseyespeech.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'Australian Capital Territory',
    city: 'Belconnen',
    practitionerType: 'Speech pathology service',
    website: 'https://www.bullseyespeech.com.au',
    sourceUrl: 'https://www.bullseyespeech.com.au/contact-and-bookings',
    relevanceNotes: 'Speech pathology provider with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Tyquin Speech and Reading Clinic',
    email: 'info@tyquin.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'Queensland',
    city: 'Bulimba',
    practitionerType: 'Speech pathology clinic',
    website: 'https://www.tyquinspeechpathology.com.au',
    sourceUrl: 'https://www.tyquinspeechpathology.com.au/contact',
    relevanceNotes: 'Speech pathology clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Flourish Speech Pathology',
    email: 'info@flourishspeechpath.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'Queensland',
    city: 'Bundaberg West',
    practitionerType: 'Speech pathology clinic',
    website: 'https://www.flourishspeechpath.com.au',
    sourceUrl: 'https://www.flourishspeechpath.com.au/contact-us/',
    relevanceNotes: 'Speech pathology clinic with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Malvern Speech Pathology',
    email: 'admin@malvernspeechpathology.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'Victoria',
    city: 'Malvern East',
    practitionerType: 'Speech pathology clinic',
    website: 'https://www.malvernspeechpathology.com',
    sourceUrl: 'https://www.malvernspeechpathology.com/contact-us',
    relevanceNotes: 'Speech pathology clinic with public admin email.',
  }),
  publicPracticeContact({
    practiceName: 'add Speech Pathology',
    email: 'stacey@addspeechpathology.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'Western Australia',
    city: 'Perth',
    practitionerType: 'Speech pathology service',
    website: 'https://www.addspeechpathology.com.au',
    sourceUrl: 'https://www.addspeechpathology.com.au/contact',
    relevanceNotes: 'Speech pathology provider with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Hearing and Speech',
    email: 'info@hearingandspeech.com.au',
    category: 'Allied Health',
    subcategory: 'Speech Pathologist',
    region: 'New South Wales',
    city: 'Queanbeyan',
    practitionerType: 'Speech pathology and hearing service',
    website: 'https://hearingandspeech.com.au',
    sourceUrl: 'https://hearingandspeech.com.au/component/phocadownload/category/1-referrals?download=1%3Aspeech-language-pathology-referral',
    relevanceNotes: 'Speech and hearing service with public enquiries email.',
  }),
  publicPracticeContact({
    practiceName: 'Kintsugi Occupational Therapy',
    email: 'nicholas@kintsugiot.com.au',
    category: 'Rehab & Disability Support',
    subcategory: 'Occupational Therapy (NDIS/rehab)',
    region: 'New South Wales',
    city: 'Newcastle',
    practitionerType: 'Occupational therapy service',
    website: 'https://www.kintsugiot.com.au',
    sourceUrl: 'https://www.kintsugiot.com.au/contact/',
    relevanceNotes: 'NDIS occupational therapy service with public contact email.',
  }),
  publicPracticeContact({
    practiceName: 'Whole-Hearted Care and Support Services',
    email: 'info@wholeheartedcare.au',
    category: 'Rehab & Disability Support',
    subcategory: 'Occupational Therapy (NDIS/rehab)',
    region: 'New South Wales',
    city: 'Merrylands',
    practitionerType: 'NDIS occupational therapy provider',
    website: 'https://www.wholeheartedcare.au',
    sourceUrl: 'https://www.wholeheartedcare.au/occupational-therapy2',
    relevanceNotes: 'NDIS provider offering occupational therapy with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Aged Care Salvos',
    email: 'agedcare.enquiries@salvationarmy.org.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Aged Care Provider',
    region: 'Australia-wide',
    city: 'Australia-wide',
    practitionerType: 'Aged care provider',
    website: 'https://agedcare.salvos.org.au',
    sourceUrl: 'https://agedcare.salvos.org.au/contact/',
    relevanceNotes: 'Aged care provider with public enquiries email.',
  }),
  publicPracticeContact({
    practiceName: 'Amicis Aged Care',
    email: 'hello@amicis.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'Australia-wide',
    city: 'Australia-wide',
    practitionerType: 'Aged care and home care provider',
    website: 'https://amicis.com.au',
    sourceUrl: 'https://amicis.com.au/contact-us',
    relevanceNotes: 'Aged care provider with public hello email.',
  }),
  publicPracticeContact({
    practiceName: 'TPG Aged Care',
    email: 'reception@tpgagedcare.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'Western Australia',
    city: 'Kingsley',
    practitionerType: 'Aged care provider',
    website: 'https://tpgagedcare.com.au',
    sourceUrl: 'https://tpgagedcare.com.au/contact-us/',
    relevanceNotes: 'Aged care support provider with public reception email.',
  }),
  publicPracticeContact({
    practiceName: 'Elite Aged Care Home Services',
    email: 'info@eliteagedcarehs.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'Queensland',
    city: 'Sanctuary Cove',
    practitionerType: 'Home care provider',
    website: 'https://www.eliteagedcarehomeservices.com.au',
    sourceUrl: 'https://www.eliteagedcarehomeservices.com.au/contact-us',
    relevanceNotes: 'Home aged care service with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'BallyCara',
    email: 'homecare@ballycara.com',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'Queensland',
    city: 'Scarborough',
    practitionerType: 'Aged care and home care provider',
    website: 'https://www.ballycara.com',
    sourceUrl: 'https://www.ballycara.com/contact-us',
    relevanceNotes: 'Aged care provider with public home care email.',
  }),
  publicPracticeContact({
    practiceName: 'Vitalis Aged Care at Home',
    email: 'info@vitalisagedcare.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'New South Wales',
    city: 'Sydney',
    practitionerType: 'Aged care at home provider',
    website: 'https://vitalisagedcare.com.au',
    sourceUrl: 'https://vitalisagedcare.com.au/',
    relevanceNotes: 'Aged care at home provider with public info email.',
  }),
  publicPracticeContact({
    practiceName: 'Choice Aged Care',
    email: 'office@choiceagedcare.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Aged Care Provider',
    region: 'Queensland',
    city: 'Spring Hill',
    practitionerType: 'Aged care services provider',
    website: 'https://www.choiceagedcare.com.au',
    sourceUrl: 'https://www.choiceagedcare.com.au/contact',
    relevanceNotes: 'Aged care services provider with public office email.',
  }),
  publicPracticeContact({
    practiceName: 'HenderCare Aged Care Services',
    email: 'mail@hendercare.com.au',
    category: 'Aged Care & Home Care',
    subcategory: 'Home Care Provider',
    region: 'Western Australia',
    city: 'West Perth',
    practitionerType: 'Aged care and disability support provider',
    website: 'https://www.hendercare.com.au',
    sourceUrl: 'https://www.agedcaremadeeasy.com.au/listings/hendercare-aged-care-services/',
    relevanceNotes: 'Aged care and disability support provider with public mail email.',
  }),
  ...categoryPracticeContacts('GPs & Doctors', [
    ['McKinley Medical Centre', 'info@mckinleymc.com.au', 'General Practitioner (GP)', 'Victoria', 'Mulgrave', 'GP medical centre', 'https://www.mckinleymc.com.au', 'https://www.mckinleymc.com.au/contact-us', 'General practice with public clinic email.'],
    ['The Junction General Practice', 'reception@thejunctiongp.com.au', 'General Practitioner (GP)', 'New South Wales', 'The Junction', 'GP medical centre', 'https://thejunctiongp.com.au', 'https://thejunctiongp.com.au/practice-information/', 'General practice with public reception email.'],
    ['Milsons Point Medical Centre', 'reception@milsonspointmedical.com.au', 'General Practitioner (GP)', 'New South Wales', 'Milsons Point', 'GP medical centre', 'https://milsonspointmedical.com.au', 'https://milsonspointmedical.com.au/contact-us/', 'General practice with public reception email.'],
    ['Forward Medical Centre', 'reception@forwardmedical.com.au', 'General Practitioner (GP)', 'South Australia', 'Adelaide', 'GP medical centre', 'https://forwardmedical.com.au', 'https://forwardmedical.com.au/patient-information/', 'GP clinic with public reception email.'],
    ['Centenary Medical Centre', 'practicemanager@centenarymedical.com.au', 'General Practitioner (GP)', 'Queensland', 'Jindalee', 'GP medical centre', 'https://www.centenarymedical.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public practice manager email.'],
    ['Hawthorn East Medical Centre', 'info@hawthorneastmedicalcentre.com.au', 'General Practitioner (GP)', 'Victoria', 'Hawthorn East', 'GP medical centre', 'https://hawthorneastmedicalcentre.com.au', 'https://hawthorneastmedicalcentre.com.au/', 'GP-owned clinic with public info email.'],
    ['Gordon Medical Centre', 'info@gordondoctors.com', 'General Practitioner (GP)', 'New South Wales', 'Gordon', 'GP medical centre', 'https://gordondoctors.com', 'https://gordondoctors.com/', 'General practice with public info email.'],
    ['Fairfield Heights Primary Health Care', 'surgery@fhphc.com.au', 'General Practitioner (GP)', 'New South Wales', 'Fairfield Heights', 'Primary health care clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public surgery email.'],
    ['OnlineDoc', 'admin@onlinedoc.com.au', 'Telehealth GP', 'Australia-wide', 'Telehealth', 'Telehealth GP service', 'https://www.onlinedoc.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed telehealth GP service with public admin email.'],
    ['Myhealth Ermington', 'ermington@myhealth.net.au', 'General Practitioner (GP)', 'New South Wales', 'Ermington', 'GP medical centre', 'https://myhealth.net.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public clinic email.'],
    ['GP Access After Hours', 'info@hunterprimarycare.com.au', 'Telehealth GP', 'New South Wales', 'Newcastle', 'After-hours GP service', 'https://hunterprimarycare.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'After-hours GP access service with public info email.'],
    ['Family Practice at Hinkler', 'familypractice.hinkler@australiandoctors.com.au', 'Family Doctor', 'Queensland', 'Bundaberg', 'Family GP clinic', 'https://www.australiandoctors.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public practice email.'],
    ['MyHealth Hampton', 'hampton.reception@myhealth.net.au', 'General Practitioner (GP)', 'Victoria', 'Hampton', 'GP medical centre', 'https://myhealth.net.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public reception email.'],
    ['Virtual Health Point', 'info@virtualhealthpoint.com.au', 'Telehealth GP', 'Australia-wide', 'Telehealth', 'Telehealth GP service', 'https://virtualhealthpoint.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Australia-wide telehealth GP service with public info email.'],
    ['After Hours Doctor Australia', 'admin@privatemedical.net', 'Telehealth GP', 'Australia-wide', 'Telehealth', 'After-hours telehealth GP service', 'https://afterhoursdoctoraustralia.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Australia-wide after-hours telehealth GP service with public admin email.'],
    ['Nunkuwarrin Yunti Wakefield Street', 'nunku@nunku.org.au', 'General Practitioner (GP)', 'South Australia', 'Adelaide', 'Community health GP service', 'https://nunku.org.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Community health service offering GP and allied health services.'],
    ['Doctor Help', 'contact@doctorhelp.com.au', 'Telehealth GP', 'Australia-wide', 'Telehealth', 'Telehealth GP service', 'https://doctorhelp.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Online GP consult service with public contact email.'],
    ['cohealth Fitzroy', 'fitzroymedical@cohealth.org.au', 'General Practitioner (GP)', 'Victoria', 'Fitzroy', 'Community GP clinic', 'https://cohealth.org.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Community GP service with public medical clinic email.'],
    ['24GP', 'admin@24gp.com.au', 'Telehealth GP', 'Australia-wide', 'Telehealth', 'Telehealth GP service', 'https://www.24gp.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Telehealth GP service with public admin email.'],
    ['Myhealth Cranbourne', 'cranbourne.reception@myhealth.net.au', 'General Practitioner (GP)', 'Victoria', 'Cranbourne', 'GP medical centre', 'https://myhealth.net.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Healthdirect-listed GP clinic with public reception email.'],
    ['Carepoint Medical Centre Darwin', 'reception@carepointmedical.com.au', 'General Practitioner (GP)', 'Northern Territory', 'Casuarina', 'GP medical centre', 'https://carepointmedical.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Darwin GP clinic with public reception email.'],
    ['First Point Healthcare', 'admin@fhc.au', 'General Practitioner (GP)', 'Tasmania', 'Newstead', 'GP medical centre', 'https://fhc.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Tasmanian GP clinic with public admin email.'],
    ['Hills Family General Practice', 'admin@hillfamilygp.net.au', 'Family Doctor', 'New South Wales', 'Castle Hill', 'Family GP clinic', 'https://hillsfamilygeneralpractice.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Family GP clinic with public admin email.'],
  ]),
  ...categoryPracticeContacts("Men's Health", [
    ["Testosterone Clinic Australia", 'info@menshealthclinic.com', 'Hormone / Testosterone Clinic', 'Australia-wide', 'Telehealth', "Men's hormone clinic", 'https://testosteroneclinic.com.au', 'https://testosteroneclinic.com.au/contact-us/', 'Testosterone clinic with public general enquiries email.'],
    ["Men's Health Melbourne", 'reception@menshealthmelbourne.com.au', 'Urologist', 'Victoria', 'Melbourne', "Men's health urology clinic", 'http://www.menshealthmelbourne.com.au', 'http://www.menshealthmelbourne.com.au/general-appointment/', "Men's health and fertility urology practice with public reception email."],
    ["First Men's Clinic", 'firstmenshealth@gmail.com', "Men's Health GP", 'New South Wales', 'Sydney', "Men's health clinic", 'https://mensmedicalclinic.com.au', 'https://mensmedicalclinic.com.au/contact/', "Men's clinic with public booking email."],
    ['Restorative Health Clinic', 'admin@rshealth.com.au', 'Sexual Health Doctor', 'Western Australia', 'Perth', "Men's sexual health clinic", 'https://rshealth.com.au', 'https://rshealth.com.au/', "Men's sexual health clinic with public admin email."],
    ['North Eastern Urology', 'referral@neu.net.au', 'Urologist', 'Victoria', 'Heidelberg', 'Urology clinic', 'https://northeasternurology.com.au', 'https://northeasternurology.com.au/patient-info/your-first-appointment/', 'Urology clinic with public referral email.'],
    ['Australian Urology Associates', 'reception@aua.com.au', 'Urologist', 'Victoria', 'Malvern', 'Urology practice', 'https://aua.com.au', 'https://aua.com.au/', 'Melbourne urology practice with public reception email.'],
    ['Kardinia Urology', 'reception@kardiniaurology.com.au', 'Urologist', 'Victoria', 'Geelong', 'Urology practice', 'https://kardiniaurology.com.au', 'https://kardiniaurology.com.au/contact-urologist-geelong/', 'Geelong urology practice with public reception email.'],
    ['Davies Urology', 'reception@daviesurology.com.au', 'Urologist', 'Tasmania', 'Hobart', 'Urology practice', 'https://www.daviesurology.com.au', 'https://www.daviesurology.com.au/contact', 'Hobart urology practice with public reception email.'],
    ['Greenslopes Urology Clinic', 'info@greenslopesurology.com.au', 'Urologist', 'Queensland', 'Brisbane', 'Urology clinic', 'https://greenslopesurology.com.au', 'https://greenslopesurology.com.au/', 'Brisbane urology clinic with public info email.'],
    ['South Terrace Urology', 'mail@sturology.com.au', 'Urologist', 'South Australia', 'Adelaide', 'Urology practice', 'https://sturology.com.au', 'https://sturology.com.au/', 'Adelaide urology specialists with public mail email.'],
    ['Katelaris Urology', 'urology@katelarisinc.com', 'Urologist', 'New South Wales', 'Sydney', 'Urology practice', 'https://www.katelarisurology.com.au', 'https://www.katelarisurology.com.au/faqs/', 'Sydney urology practice with public appointment email.'],
    ['Goldfields Urology', 'reception@goldfieldsurology.com.au', 'Urologist', 'Victoria', 'Bendigo', 'Urology practice', 'https://www.goldfieldsurology.com.au', 'https://awomansurologist.com.au/find-a-urologist/', 'Urology practice listed with public reception email.'],
    ['Melbourne Urology Consultants', 'reception@melbourneurology.net.au', 'Urologist', 'Victoria', 'East Melbourne', 'Urology practice', 'https://www.melbourneurology.net.au', 'https://awomansurologist.com.au/find-a-urologist/', 'Urology consultants listed with public reception email.'],
    ['Dr Sandra Elmer Urology', 'admin@drsandraelmerurology.com.au', 'Urologist', 'Victoria', 'East Melbourne', 'Urology practice', 'https://www.drsandraelmerurology.com.au', 'https://awomansurologist.com.au/find-a-urologist/', 'Urology practice listed with public admin email.'],
    ['Ballarat Urology', 'info@ballaraturology.com.au', 'Urologist', 'Victoria', 'Ballarat', 'Urology practice', 'https://www.ballaraturology.com.au', 'https://awomansurologist.com.au/find-a-urologist/', 'Regional urology practice with public info email.'],
  ]),
  ...categoryPracticeContacts('Allied Health', [
    ['Allied AU', 'support@alliedhealthau.com', 'Occupational Therapist (OT)', 'Australia-wide', 'Australia-wide', 'Allied health provider', 'https://alliedhealthau.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Multi-discipline allied health provider with public support email.'],
    ['Head2toe Physiotherapy and Podiatry', 'info@head2toe.com.au', 'Physiotherapist', 'Victoria', 'Brunswick', 'Physiotherapy and podiatry clinic', 'https://head2toe.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Physio and podiatry clinic with public info email.'],
    ['Physiotas Shearwater', 'info@physiotas.com.au', 'Physiotherapist', 'Tasmania', 'Shearwater', 'Physiotherapy clinic', 'https://physiotas.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Physiotherapy clinic with public info email.'],
    ['Talking Heads Speech Pathology Miranda', 'enquiries@talkingheads.net.au', 'Speech Pathologist', 'New South Wales', 'Miranda', 'Speech pathology clinic', 'https://talkingheads.net.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology clinic with public enquiries email.'],
    ['Speech Pathology Tasmania Hobart', 'speech@spt.com.au', 'Speech Pathologist', 'Tasmania', 'Hobart', 'Speech pathology clinic', 'https://spt.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology clinic with public speech email.'],
    ['Neuro SLP', 'belinda@neuroslp.com.au', 'Speech Pathologist', 'Australia-wide', 'Telehealth', 'Neurological speech pathology service', 'https://neuroslp.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Mobile and telehealth adult neuro speech pathology service.'],
    ['Straight Talk Speech Pathology', 'clinic@straighttalkspeech.com.au', 'Speech Pathologist', 'Western Australia', 'Gosnells', 'Speech pathology clinic', 'https://straighttalkspeech.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology clinic with public clinic email.'],
    ['Talking Point Speech Pathology', 'shilpa@talkingpointspeechpathology.com.au', 'Speech Pathologist', 'Victoria', 'Glen Iris', 'Speech pathology clinic', 'https://talkingpointspeechpathology.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology service with public booking email.'],
    ['Hunter Speech Pathology', 'nikki.stambolie@hunterspeechpathology.com', 'Speech Pathologist', 'New South Wales', 'Maitland', 'Speech pathology clinic', 'https://hunterspeechpathology.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology service with public contact email.'],
    ['Connect the Words Speech Pathology', 'connectthewords@gmail.com', 'Speech Pathologist', 'Queensland', 'Elanora', 'Speech pathology clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Adult communication and swallowing speech pathology provider.'],
    ['Sharon Linehan Speech Pathology', 'sharonlinehanspeechpathology@gmail.com', 'Speech Pathologist', 'New South Wales', 'Tumbi Umbi', 'Speech pathology clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology provider with public contact email.'],
    ['Speak Read Learn Speech Pathology', 'speakreadlearnspeechpathology@gmail.com', 'Speech Pathologist', 'Victoria', 'Belmont', 'Speech pathology clinic', 'https://www.speakreadlearnspeechpathology.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Paediatric speech pathology clinic with public contact email.'],
    ['Karen Kostal Speech Pathology', 'karenkostal5@gmail.com', 'Speech Pathologist', 'New South Wales', 'Tintenbar', 'Speech pathology clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology service for adults and children.'],
    ['Access Speech Pathology Services', 'accessspeechpath@yahoo.com', 'Speech Pathologist', 'Northern Territory', 'Millner', 'Speech pathology clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'NDIS registered speech pathology service.'],
    ['Di Rinne Speech Pathology', 'dirinnespeech@optusnet.com.au', 'Speech Pathologist', 'New South Wales', 'Cherrybrook', 'Speech pathology clinic', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology provider with public contact email.'],
    ['Adelaide Pendlebury Speech Pathology', 'adelaide@adelaidependlebury.com.au', 'Speech Pathologist', 'New South Wales', 'Pyrmont', 'Speech pathology clinic', 'https://www.adelaidependlebury.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech pathology provider with public email.'],
    ['Ability Occupational Therapy', 'admin@abilityot.com.au', 'Occupational Therapist (OT)', 'Queensland', 'Brisbane', 'Occupational therapy provider', 'https://abilityot.com.au', 'https://abilityot.com.au/contact-us/', 'Occupational therapy provider with public admin email.'],
    ['Kadia Occupational Therapy', 'support@kadia.com.au', 'Occupational Therapist (OT)', 'Australia-wide', 'Australia-wide', 'Occupational therapy provider', 'https://kadia.com.au', 'https://kadia.com.au/contact-kadia/', 'Occupational therapy provider with public support email.'],
    ['Connecting Lives OT', 'hello@connectinglivesot.com.au', 'Occupational Therapist (OT)', 'Queensland', 'Grange', 'Occupational therapy provider', 'https://www.connectinglivesot.com.au', 'https://www.connectinglivesot.com.au/contact', 'OT provider with public hello email.'],
    ['Stepping Stones OT', 'admin@steppingstonesot.com.au', 'Occupational Therapist (OT)', 'New South Wales', 'Mount Pritchard', 'Occupational therapy provider', 'https://steppingstonesot.com.au', 'https://steppingstonesot.com.au/contact-us/', 'Occupational therapy provider with public admin email.'],
    ["Doreen's OT", 'admin@doreensot.com.au', 'Occupational Therapist (OT)', 'Victoria', 'Geelong', 'Occupational therapy provider', 'https://doreensot.com.au', 'https://doreensot.com.au/contact-us/', 'Occupational therapy provider with public admin email.'],
    ['Direct Occupational Therapy Services', 'admin@directot.com.au', 'Occupational Therapist (OT)', 'South Australia', 'Adelaide', 'Occupational therapy provider', 'https://directot.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Occupational therapy service with public admin email.'],
  ]),
  ...categoryPracticeContacts('Mental Health', [
    ['Australia Telehealth', 'office@australiatelehealth.com.au', 'Psychiatrist', 'Australia-wide', 'Telehealth', 'Telehealth psychiatry service', 'https://australiatelehealth.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Telehealth psychiatry service with public office email.'],
    ['Connecting Minds Clinic', 'connectingmindsclinic@gmail.com', 'Psychiatrist', 'Australia-wide', 'Telehealth', 'Psychiatry clinic', 'https://connectingmindsclinic.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Mental health clinic with public contact email.'],
    ['Talk With Tara Social Work and Counselling', 'tara@talkwithtara.com.au', 'Mental Health Social Worker', 'Queensland', 'Varsity Lakes', 'Social work and counselling provider', 'https://talkwithtara.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Counselling and social work service with public email.'],
    ['Healing Place Psychology Practice', 'katherine@healingplacepsychology.com.au', 'Clinical Psychologist', 'Australia-wide', 'Telehealth', 'Clinical psychology practice', 'https://healingplacepsychology.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Clinical psychology service with public contact email.'],
    ['Connecting You Psychology', 'engage@connectingyoupsychology.com.au', 'Psychologist', 'New South Wales', 'Erina', 'Psychology practice', 'https://connectingyoupsychology.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology practice with public engagement email.'],
    ['Lynsey Byrom Clinical Psychology', 'reception@lynseybyrom.com.au', 'Clinical Psychologist', 'Queensland', 'Ashmore', 'Clinical psychology practice', 'https://lynseybyrom.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Clinical psychology practice with public reception email.'],
    ['Clinical Psychology Melbourne', 'admin@psyclinical.com', 'Clinical Psychologist', 'Victoria', 'Melbourne', 'Clinical psychology clinic', 'https://psyclinical.com', 'https://www.healthdirect.gov.au/australian-health-services', 'Clinical psychology clinic with public admin email.'],
    ['Mind and Health Psychology', 'mindandhealthpsychology@gmail.com', 'Psychologist', 'New South Wales', 'Broadmeadow', 'Psychology practice', 'https://mindandhealthpsychology.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology practice with public contact email.'],
    ['Wellvue', 'referrals@wellvue.com.au', 'Psychiatrist', 'Australia-wide', 'Telehealth', 'Telehealth psychiatry and psychology service', 'https://wellvue.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Telehealth mental health provider with public referrals email.'],
    ['Supported Minds Psychology', 'info@supportedminds.com.au', 'Psychologist', 'South Australia', 'Adelaide', 'Psychology clinic', 'https://supportedminds.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology clinic with public info email.'],
    ['Darren Bartlett Clinical Psychologist', 'dbartlettpsychology@gmail.com', 'Clinical Psychologist', 'New South Wales', 'Coffs Harbour', 'Clinical psychology practice', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Clinical psychology provider with public contact email.'],
    ['Dr Helen Stallman', 'psychology@carecollaborateconnect.org.au', 'Clinical Psychologist', 'Australia-wide', 'Telehealth', 'Clinical psychology service', 'https://www.drhelenstallman.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Telehealth clinical psychology service with public email.'],
    ['Jacqueline Landre Psychology', 'jlandrepsych@gmail.com', 'Psychologist', 'Western Australia', 'Osborne Park', 'Psychology practice', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology provider with public contact email.'],
    ['Medical Wisdom', 'drsuejbaker@gmail.com', 'Mental Health Social Worker', 'Australia-wide', 'Telehealth', 'Focused psychological strategies provider', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Telehealth mental wellbeing provider with public email.'],
    ['David Joyce Psychology', 'david@headfirstpsychology.com.au', 'Psychologist', 'New South Wales', 'Leichhardt', 'Psychology practice', 'https://headfirstpsychology.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology provider with public contact email.'],
    ['Fabiola Bedon Clinical Psychologist', 'fabiola.bedon@bigpond.com', 'Clinical Psychologist', 'New South Wales', 'Brookvale', 'Clinical psychology practice', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Clinical psychology provider with public email.'],
    ['Helen Fuller Psychology', 'helenfullerpsychology@gmail.com', 'Psychologist', 'New South Wales', 'Narrabeen', 'Psychology practice', 'https://www.healthdirect.gov.au/australian-health-services', 'https://www.healthdirect.gov.au/australian-health-services', 'Psychology provider with public contact email.'],
    ['Family Nurture', 'reception@familynurture.com.au', 'Family Therapist', 'Queensland', 'Pacific Pines', 'Multidisciplinary mental health clinic', 'https://familynurture.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Family mental health clinic with public reception email.'],
  ]),
  ...categoryPracticeContacts('Musculoskeletal & Pain', [
    ['Backpain.com.au', 'info@myotherapy.com.au', 'Spinal / Back Pain Clinic', 'Queensland', 'Varsity Lakes', 'Back pain therapy provider', 'https://www.backpain.com.au', 'https://www.backpain.com.au/contact/', 'Back pain education and therapy provider with public info email.'],
    ['Metro Pain Melbourne', 'admin@metropain.com.au', 'Pain Specialist', 'Victoria', 'Clayton', 'Pain management clinic', 'https://www.metropain.com.au', 'https://www.metropain.com.au/contact', 'Pain specialist clinic with public admin email.'],
    ['MiPain', 'reception@mipain.com.au', 'Pain Specialist', 'Queensland', 'Pimlico', 'Pain management clinic', 'https://mipain.com.au', 'https://mipain.com.au/contact-us/', 'Pain clinic with public reception email.'],
    ['Metro Pain Queensland', 'admin@metropainqld.com.au', 'Pain Specialist', 'Queensland', 'Bowen Hills', 'Pain management clinic', 'https://www.metropain.com.au', 'https://www.metropain.com.au/brisbane-clinic-contact', 'Pain specialist clinic with public QLD admin email.'],
    ['Mind Body Pain Specialists', 'reception@mbpain.com.au', 'Pain Specialist', 'Victoria', 'Heidelberg Heights', 'Pain specialist clinic', 'https://mbpain.com.au', 'https://mbpain.com.au/contact/', 'Pain specialist clinic with public reception email.'],
    ['Body & Brain Centre', 'info@bodybraincentre.com.au', 'Remedial Massage', 'Victoria', 'Moonee Ponds', 'Multidisciplinary musculoskeletal clinic', 'https://www.bodybraincentre.com.au', 'https://www.bodybraincentre.com.au/services/remedial-massage', 'Clinic offering remedial massage, chiropractic, acupuncture, osteopathy and related services.'],
  ]),
  ...categoryPracticeContacts('Rehab & Disability Support', [
    ['Better Rehab Arundel', 'admin@betterrehab.com.au', 'Occupational Therapy (NDIS/rehab)', 'Queensland', 'Arundel', 'NDIS allied health provider', 'https://betterrehab.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'NDIS allied health provider with OT, speech, physio and support services.'],
    ['Barefoot Therapists', 'admin@barefoottherapists.com.au', 'Occupational Therapy (NDIS/rehab)', 'Victoria', 'Rosebud', 'NDIS allied health provider', 'https://barefoottherapists.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'NDIS OT and speech therapy provider with public admin email.'],
    ['St Giles Launceston', 'stgilessociety@stgiles.org.au', 'Disability Support Provider', 'Tasmania', 'Launceston', 'Disability and allied health provider', 'https://stgiles.org.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Disability and allied health provider with public society email.'],
    ['Dee Wardrop Speech Pathology and Occupational Therapy', 'reception@deewardrop.com.au', 'Occupational Therapy (NDIS/rehab)', 'Victoria', 'Footscray', 'Speech and occupational therapy clinic', 'https://deewardrop.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Speech and OT provider with public reception email.'],
    ['Leading Therapies', 'info@leadingtherapies.com.au', 'Physiotherapy (rehab)', 'New South Wales', 'Home visit', 'Mobile allied health provider', 'https://leadingtherapies.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Mobile allied health service for community and aged care clients.'],
    ['Physio Pal', 'admin@physiopal.com.au', 'Physiotherapy (rehab)', 'New South Wales', 'Gerringong', 'Mobile physiotherapy provider', 'https://physiopal.com.au', 'https://physiopal.com.au/contact-us/', 'Mobile healthcare and aged-care rehabilitation provider.'],
    ['Olympus Care', 'info@olympuscare.com.au', 'Home Care Provider', 'Australia-wide', 'Mobile', 'Mobile physiotherapy and home care provider', 'https://olympuscare.com.au', 'https://olympuscare.com.au/our-services/', 'Mobile physiotherapy and home support provider with public info email.'],
    ['Nomad Physio', 'info@nomadphysio.com.au', 'Physiotherapy (rehab)', 'New South Wales', 'Sydney', 'Mobile physiotherapy provider', 'https://nomadphysio.com.au', 'https://nomadphysio.com.au/home-care-package-physiotherapy-sydney/', 'Mobile home-care package physiotherapy provider.'],
    ['Physihome', 'care@physihome.com.au', 'Physiotherapy (rehab)', 'New South Wales', 'Sydney', 'Mobile physiotherapy provider', 'https://physihome.com.au', 'https://physihome.com.au/faq-1', 'Mobile physiotherapy provider with public care email.'],
  ]),
  ...categoryPracticeContacts('Nutrition & Metabolic Health', [
    ['Start Organic Health', 'hello@startorganichealth.com', 'Clinical Nutritionist', 'Victoria', 'Ocean Grove', 'Clinical nutritionist', 'https://www.startorganichealth.com.au', 'https://www.startorganichealth.com.au/', 'Clinical nutrition service with public hello email.'],
    ['Murray Mallee Community Health', 'murraymalleecommunityhealth@sa.gov.au', 'Diabetes Educator', 'South Australia', 'Murray Bridge', 'Community health allied health service', 'https://www.sahealth.sa.gov.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Community health service offering dietetics and diabetes education.'],
    ['Nutritionally Balanced', 'reem@nutritionallybalanced.com.au', 'Diabetes Educator', 'Australia-wide', 'Telehealth', 'Dietitian and diabetes educator', 'https://nutritionallybalanced.com.au', 'https://www.healthdirect.gov.au/australian-health-services', 'Dietitian and credentialed diabetes educator with public contact email.'],
  ]),
  ...categoryPracticeContacts('Holistic & Integrative', [
    ['Floralia Wellness', 'hello@floraliawellness.com.au', 'Naturopath', 'Western Australia', 'Perth', 'Naturopathic and integrative clinic', 'https://floraliawellness.com.au', 'https://floraliawellness.com.au/', 'Integrative naturopathic clinic with public reception email.'],
    ['Melbourne Natural Medicine Clinic', 'info@melbournenaturalmedicine.com.au', 'Naturopath', 'Victoria', 'South Melbourne', 'Natural medicine clinic', 'https://www.melbournenaturalmedicine.com.au', 'https://www.melbournenaturalmedicine.com.au/', 'Natural medicine clinic with public info email.'],
    ['My Naturopath Gold Coast', 'info@mynaturopathgoldcoast.com.au', 'Naturopath', 'Queensland', 'Burleigh Waters', 'Naturopathic clinic', 'https://mynaturopathgoldcoast.com.au', 'https://mynaturopathgoldcoast.com.au/services/naturopathy/', 'Naturopathic clinic with public info email.'],
    ['Scott Collins Naturopath', 'hello@scottcollins.com.au', 'Naturopath', 'Queensland', 'Nambour', 'Naturopathic clinic', 'https://scottcollins.com.au', 'https://scottcollins.com.au/', 'Naturopathic clinic with public hello email.'],
    ['Vibe Natural Health', 'info@vibenaturalhealth.com.au', 'Integrative GP/Doctor', 'Queensland', 'Grange', 'Holistic GP clinic', 'https://vibenaturalhealth.com.au', 'https://vibenaturalhealth.com.au/', 'Holistic GP clinic with public info email.'],
    ['Adelaide Naturopathic', 'admin@adelaidenaturopathic.com.au', 'Naturopath', 'South Australia', 'Glenelg East', 'Naturopathic clinic', 'https://adelaidenaturopathic.com.au', 'https://adelaidenaturopathic.com.au/', 'Naturopathic clinic with public admin email.'],
    ['All Naturopath', 'angie@allnaturopath.com.au', 'Naturopath', 'Victoria', 'Surrey Hills', 'Naturopathic clinic', 'https://allnaturopath.com.au', 'https://allnaturopath.com.au/contact/', 'Naturopathic clinic with public contact email.'],
  ]),
  ...categoryPracticeContacts('Dental & Oral Health', [
    ['Foundation Dental Services', 'admin@foundationdental.com.au', 'Periodontist', 'Queensland', 'Brisbane', 'Periodontal and dental implant clinic', 'https://www.foundationdental.com.au', 'https://www.foundationdental.com.au/contact/', 'Periodontics and implant clinic with public admin email.'],
    ['NorthShore Dental Care', 'info@northshoredental.com.au', 'Dentist', 'Queensland', 'Paradise Point', 'Dental clinic', 'https://northshoredental.com.au', 'https://northshoredental.com.au/contact/', 'Dental clinic with public info email.'],
    ['Mount Lawley Dental', 'reception@mountlawleydental.com.au', 'Dentist', 'Western Australia', 'Mount Lawley', 'Dental clinic', 'https://www.mountlawleydental.com.au', 'https://www.mountlawleydental.com.au/contact-us', 'Dental clinic with public reception email.'],
    ['Smith Street Dental Darwin', 'reception@smithstreetdental.com', 'Dentist', 'Northern Territory', 'Darwin', 'Dental clinic', 'https://smithstreetdental.com', 'https://smithstreetdental.com/contact/', 'Dental clinic with public reception email.'],
    ['Croydon Dental Clinic', 'info@croydondentalclinic.com.au', 'Dentist', 'Victoria', 'Croydon', 'Dental clinic', 'https://www.croydondentalclinic.com.au', 'https://www.croydondentalclinic.com.au/contact-us/', 'Dental clinic with public email link.'],
    ['Pullen Dental', 'info@pullendental.com.au', 'Dentist', 'Queensland', 'Maryborough', 'Dental clinic', 'https://www.pullendental.com.au', 'https://www.pullendental.com.au/contact-us/', 'Dental clinic with public email link.'],
  ]),
  ...categoryPracticeContacts('Eye & Hearing', [
    ['Helix Hearing', 'hello@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Gippsland', 'Hearing clinic group', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic group with public hello email.'],
    ['Helix Hearing Warragul', 'warragul@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Warragul', 'Hearing clinic', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic location with public email.'],
    ['Helix Hearing Morwell', 'morwell@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Morwell', 'Hearing clinic', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic location with public email.'],
    ['Helix Hearing Traralgon', 'traralgon@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Traralgon', 'Hearing clinic', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic location with public email.'],
    ['Helix Hearing Bairnsdale', 'bairnsdale@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Bairnsdale', 'Hearing clinic', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic location with public email.'],
    ['Helix Hearing Richmond', 'richmond@helixhearing.com.au', 'Hearing Clinic', 'Victoria', 'Richmond', 'Hearing clinic', 'https://www.helixhearing.com.au', 'https://www.helixhearing.com.au/contact/', 'Hearing clinic location with public email.'],
    ['Centre for Hearing', 'info@centreforhearing.com.au', 'Audiologist', 'New South Wales', 'Bowral', 'Audiology clinic', 'https://centreforhearing.com.au', 'https://centreforhearing.com.au/contact/', 'Audiologist-owned hearing clinic with public info email.'],
    ['Darwin Ears and Hearing', 'info@darwinears.com.au', 'Audiologist', 'Northern Territory', 'Driver', 'Audiology clinic', 'https://darwinears.com.au', 'https://darwinears.com.au/contact-%26-referral', 'Audiology clinic with public info email.'],
    ['Victorian Hearing Geelong', 'info@victorianhearing.com.au', 'Audiologist', 'Victoria', 'Geelong', 'Audiology clinic', 'https://victorianhearing.com.au', 'https://victorianhearing.com.au/geelong/', 'Audiology clinic with public info email.'],
    ['Hearing Aid Specialists SA', 'enquiries@hassa.com.au', 'Hearing Clinic', 'South Australia', 'Adelaide', 'Hearing clinic group', 'https://hassa.com.au', 'https://hassa.com.au/contact/', 'South Australian hearing clinic group with public enquiries email.'],
  ]),
  ...categoryPracticeContacts('Diagnostics & Testing', [
    ['Sullivan Nicolaides Pathology', 'doctors_services@snp.com.au', 'Pathology / Lab Testing', 'Queensland', 'Bowen Hills', 'Pathology service', 'https://www.snp.com.au', 'https://www.snp.com.au/contact/', 'Pathology service with public doctor services email.'],
    ['San Radiology and Nuclear Medicine', 'radiologybookings@sah.org.au', 'Imaging / Radiology (X-ray, CT, MRI, Ultrasound)', 'New South Wales', 'Wahroonga', 'Radiology service', 'https://sanheart.org.au', 'https://sanheart.org.au/contact-san-radiology/', 'Radiology service with public bookings email.'],
    ['San Nuclear Medicine and PET-CT', 'nmadmin@sah.org.au', 'Imaging / Radiology (X-ray, CT, MRI, Ultrasound)', 'New South Wales', 'Wahroonga', 'Nuclear medicine service', 'https://sanheart.org.au', 'https://sanheart.org.au/contact-san-radiology/', 'Nuclear medicine service with public admin email.'],
    ['Eastern Health Pathology', 'pathologyadmin@easternhealth.org.au', 'Pathology / Lab Testing', 'Victoria', 'Box Hill', 'Pathology service', 'https://www.easternhealth.org.au', 'https://www.easternhealth.org.au/pathology-3/for-patients/pathology-contact-us/', 'Pathology service with public admin email.'],
    ['Darwin Respiratory and Sleep Health', 'admin@darwinressleep.com', 'Sleep Study Clinic', 'Northern Territory', 'Darwin', 'Sleep and respiratory clinic', 'https://darwinsleephealth.com.au', 'https://darwinsleephealth.com.au/contact-us/', 'Sleep and respiratory clinic with public admin email.'],
    ['Nepean Lung and Sleep', 'reception@nlsleep.com.au', 'Sleep Study Clinic', 'New South Wales', 'Kingswood', 'Sleep and lung clinic', 'https://nepeanlungandsleep.com.au', 'https://nepeanlungandsleep.com.au/contact/', 'Sleep and respiratory testing clinic with public reception email.'],
    ['Thoracic and Sleep Group Queensland', 'admin@tsgq.com.au', 'Sleep Study Clinic', 'Queensland', 'Auchenflower', 'Sleep and lung function clinic', 'https://thoracicandsleep.com.au', 'https://thoracicandsleep.com.au/contact/', 'Sleep centre and lung function clinic with public admin email.'],
    ['Wesley Lung Function Lab', 'lung@tsgq.com.au', 'Cardiac Testing (ECG/Holter) Clinic', 'Queensland', 'Auchenflower', 'Lung function testing service', 'https://thoracicandsleep.com.au', 'https://thoracicandsleep.com.au/contact/', 'Lung function testing service with public email.'],
    ['Cardiac and Vascular Diagnostic Centre', 'cardiacdiagnosticschermside@gmail.com', 'Cardiac Testing (ECG/Holter) Clinic', 'Queensland', 'Chermside', 'Cardiac diagnostics clinic', 'https://cardiac-diagnostics.com.au', 'https://cardiac-diagnostics.com.au/', 'Cardiac and vascular diagnostics clinic with public email.'],
  ]),
  ...categoryPracticeContacts('Pharmacy & Medication Support', [
    ['Prime Compounding Pharmacy', 'info@primecompounding.com.au', 'Compounding Pharmacy', 'Queensland', 'Dayboro', 'Compounding pharmacy', 'https://www.primecompounding.com.au', 'https://www.primecompounding.com.au/contact-us', 'Compounding pharmacy with public info email.'],
    ['Orrong Compounding Pharmacy', 'info@orrongpharmacy.com', 'Compounding Pharmacy', 'Victoria', 'Prahran', 'Compounding pharmacy', 'https://orrongpharmacy.com', 'https://orrongpharmacy.com/compounding-pharmacy-melbourne/', 'Compounding pharmacy with public info email.'],
    ['Kanan Pharmacy', 'kananpharmacy1@gmail.com', 'Pharmacy', 'New South Wales', 'Punchbowl', 'Community pharmacy', 'https://www.kananpharmacy.com.au', 'https://www.kananpharmacy.com.au/contact-us', 'Community and compounding pharmacy with public email.'],
    ['Scott Street Pharmacy Front Shop', 'frontshop@scottstreetpharmacy.com.au', 'Pharmacy', 'Queensland', 'Toowoomba', 'Community pharmacy', 'https://www.scottstreetpharmacy.com.au', 'https://www.scottstreetpharmacy.com.au/', 'Community pharmacy with public front shop email.'],
    ['Scott Street Pharmacy Pharmacist Advice', 'pharmacist@scottstreetpharmacy.com.au', 'Medication Review Pharmacist', 'Queensland', 'Toowoomba', 'Pharmacist advice service', 'https://www.scottstreetpharmacy.com.au', 'https://www.scottstreetpharmacy.com.au/', 'Pharmacy with public pharmacist advice email.'],
  ]),
  ...categoryPracticeContacts('Aged Care & Home Care', [
    ['HammondCare', 'support@hammond.com.au', 'Aged Care Provider', 'Australia-wide', 'Australia-wide', 'Aged care and home care provider', 'https://www.hammond.com.au', 'https://www.hammond.com.au/contact', 'Aged care provider with public support email.'],
    ['Ozcare', 'info@ozcare.org.au', 'Aged Care Provider', 'Queensland', 'Brisbane', 'Aged care and home care provider', 'https://ozcare.org.au', 'https://ozcare.org.au/contact-us/', 'Aged care provider with public info email.'],
    ['Benetas', 'customercentre@benetas.com.au', 'Aged Care Provider', 'Victoria', 'Hawthorn East', 'Aged care and home care provider', 'https://www.benetas.com.au', 'https://www.benetas.com.au/contact-us', 'Aged care provider with public customer centre email.'],
    ['Hub and Spoke Health', 'admin@hubandspoke.health', 'Mobile Physio', 'Victoria', 'Melbourne', 'Mobile allied health provider', 'https://hubandspoke.health', 'https://hubandspoke.health/aged-care-mobile-physiotherapy/', 'Mobile allied health provider supporting aged care physiotherapy.'],
    ['Regis Aged Care', 'regis@regis.com.au', 'Aged Care Provider', 'Australia-wide', 'Australia-wide', 'Aged care provider', 'https://www.regis.com.au', 'https://pilot.regis.com.au/contact-us/', 'Aged care provider with public national office email.'],
    ['St Nicholas Seniors Care Centre', 'admin@acare.au', 'Aged Care Provider', 'New South Wales', 'Punchbowl', 'Aged care provider', 'https://www.acare.au', 'https://www.acare.au/contact/', 'Seniors care provider with public admin email.'],
  ]),
]
